### ISSUE TITLE
Ubuntu 17.04 is not supported

### ISSUE THREAD

**Issue by mohammedi-haroune** [cs50/libcs50#100]
Trying to install the library in my Ubuntu 17.04 machine and also with some other machines with Ubuntu 17.4 but seems like in not yet supported because I'm always facing the following problem 
```
W: The repository 'http://ppa.launchpad.net/cs50/ppa/ubuntu zesty Release' does not have a Release file.
E: Failed to fetch http://ppa.launchpad.net/cs50/ppa/ubuntu/dists/zesty/main/source/Sources  404  Not Found
```
which cause this problem `E: Unable to locate package libcs50` when attempting to install it using `sudo apt-get install libcs50`  as mensioned in the REDME file.

Thanks in advance

**Comment by kzidane** [comment]
Sorry for the inconvenience! We'll resolve that asap!

https://github.com/cs50/libcs50/issues/100

**Comment by kzidane** [comment]
Just manually re-packaged and deployed for Zesty. This should be fixed now. The package should be auto-deployed for Zesty starting next release. Please let me know if you're still experiencing this problem! Thank you!

**Comment by mohammedi-haroune** [comment]
problem solved thanks a lot
