### ISSUE TITLE
Mac Installation

### ISSUE THREAD

**Issue by theodoretliu** [cs50/libcs50#105]
Currently, the Makefile does not support Mac. This includes incompatibilities with `-soname`, `install -D` and `asciidoctor`. Solutions to the first two problems can be found [here](https://stackoverflow.com/questions/4580789/ld-unknown-option-soname-on-os-x) and [here](https://apple.stackexchange.com/questions/201029/install-illegal-option-d). No idea on the last problem. There are most likely other problems, but this is where I stopped trying to fix it.

A lot of students in CS50 will most likely be using Macs, so I think this is important. I understand the Cloud9 platform is there, but I think this option should be available if the student desires. I'd be happy to work on this!

**Comment by theodoretliu** [comment]
An updated build snippet
```
.PHONY: build
build: clean
	$(CC) -c -fPIC -std=c99 -Wall -o cs50.o src/cs50.c
	$(CC) -shared -Wl,-install_name,$(SONAME) -o libcs50.so.$(VERSION) cs50.o
	rm -f cs50.o
	ln -s libcs50.so.$(VERSION) $(SONAME)
	ln -s $(SONAME) libcs50.so
	ginstall -D -m 644 src/cs50.h build/include/cs50.h
	mkdir -p build/lib build/src/libcs50
	mv libcs50.so* build/lib
	cp -r src/* build/src/libcs50
```

Note the change from `-soname` to `-install_name` and the change from `install` to `ginstall`. Before running `make install` the user needs to have `brew`. Then they can run
1. `brew install coreutils` - this gets `ginstall`
2. `brew install ruby`
3. `gem install asciidoctor` - this gets `asciidoctor` for Macs
I haven't tested this fully, but these are the steps I took to make this work.

**Comment by crossroads1112** [comment]
Thanks for reporting this! We actually already have a PR which addresses this #97. Feel free to comment there!
