### ISSUE TITLE
README does not indicate that sudo is needed for macOS

### ISSUE THREAD

**Issue by americanhanko** [cs50/libcs50#108]
As shown in https://github.com/cs50/libcs50/pull/97

**Comment by crossroads1112** [comment]
Is `/usr/local/*` not writable by user in OSX?

**Comment by americanhanko** [comment]
`/usr/local` is owned by root, but its contents don't have to be. This is why we see Homebrew create `/usr/local/Cellar`, make the user the owner, and then symlink the package contents to the appropriate directories.

**Comment by crossroads1112** [comment]
Fixed in #127. Forgot to close this.
