### ISSUE TITLE
Unable to locate package libcs50

### ISSUE THREAD

**Issue by sasakuvac** [cs50/libcs50#113]
Could someone help me with this, please? I am using Ubuntu 16.04. When I follow steps from "read me", I got this:

sudo apt-get install libcs50
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libcs50

**Comment by dmalan** [comment]
Hi, did you definitely run

```
sudo apt-add-repository ppa:cs50/ppa
sudo apt-get update
```

first?

**Comment by sasakuvac** [comment]
Hello, thanks for reply. Yes, of course.

**Comment by dmalan** [comment]
Exactly what was the output of

```
sudo apt-add-repository ppa:cs50/ppa
sudo apt-get update
```

on your machine? I just tried on a clean installation of Ubuntu 16.04, and those commands indeed worked (once I had `apt-add-repository` installed)!

**Comment by sasakuvac** [comment]
**sudo apt-get install software-properties-common whiptail**
[sudo] password for sasa: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
whiptail is already the newest version (0.52.18-1ubuntu2).
software-properties-common is already the newest version (0.96.20.7).
The following packages were automatically installed and are no longer required:
  linux-headers-4.10.0-28 linux-headers-4.10.0-28-generic
  linux-image-4.10.0-28-generic linux-image-extra-4.10.0-28-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.

**sudo apt-add-repository ppa:cs50/ppa**
 
 More info: https://launchpad.net/~cs50/+archive/ubuntu/ppa
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keyring `/tmp/tmpiasnbdui/secring.gpg' created
gpg: keyring `/tmp/tmpiasnbdui/pubring.gpg' created
gpg: requesting key 4A0E822C from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpiasnbdui/trustdb.gpg: trustdb created
gpg: key 4A0E822C: public key "Launchpad PPA for CS50" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK

**sudo apt-get update**

Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]     
Hit:2 http://ba.archive.ubuntu.com/ubuntu xenial InRelease                     
Get:3 http://ba.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]    
Get:4 http://ba.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]  
Get:5 http://security.ubuntu.com/ubuntu xenial-security/restricted i386 Packages [7492 B]
Get:6 http://security.ubuntu.com/ubuntu xenial-security/restricted Translation-en [2412 B]
Get:7 http://security.ubuntu.com/ubuntu xenial-security/universe i386 Packages [152 kB]
Get:8 http://ba.archive.ubuntu.com/ubuntu xenial-updates/main i386 Packages [611 kB]
Get:9 http://security.ubuntu.com/ubuntu xenial-security/universe Translation-en [93,0 kB]
Get:10 http://security.ubuntu.com/ubuntu xenial-security/multiverse i386 Packages [3396 B]
Get:11 http://security.ubuntu.com/ubuntu xenial-security/multiverse Translation-en [1336 B]
Hit:12 http://ppa.launchpad.net/cs50/ppa/ubuntu xenial InRelease               
Get:13 http://ba.archive.ubuntu.com/ubuntu xenial-updates/main Translation-en [269 kB]
Get:14 http://ba.archive.ubuntu.com/ubuntu xenial-updates/main i386 DEP-11 Metadata [305 kB]
Get:15 http://ba.archive.ubuntu.com/ubuntu xenial-updates/main DEP-11 64x64 Icons [217 kB]
Hit:16 https://download.sublimetext.com apt/stable/ InRelease  
Get:17 http://ba.archive.ubuntu.com/ubuntu xenial-updates/universe i386 Packages [516 kB]
Get:18 http://ba.archive.ubuntu.com/ubuntu xenial-updates/universe i386 DEP-11 Metadata [173 kB]
Get:19 http://ba.archive.ubuntu.com/ubuntu xenial-updates/universe DEP-11 64x64 Icons [240 kB]
Get:20 http://ba.archive.ubuntu.com/ubuntu xenial-updates/multiverse i386 DEP-11 Metadata [7080 B]
Get:21 http://ba.archive.ubuntu.com/ubuntu xenial-backports/main i386 DEP-11 Metadata [3328 B]
Get:22 http://ba.archive.ubuntu.com/ubuntu xenial-backports/universe i386 DEP-11 Metadata [4584 B]
Fetched 2912 kB in 4s (722 kB/s)                              
Reading package lists... Done

**sudo apt-get install libcs50**

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libcs50

**Comment by kzidane** [comment]
@sasakuvac what's the output of running these commands?

```
$ lsb_release -a
$ cat /etc/apt/sources.list
$ cat /etc/apt/sources.list.d/cs50-ubuntu-ppa-xenial.list
```

**Comment by kzidane** [comment]
@sasakuvac and also can you try running the following commands too?

```
$ sudo rm -rf /var/lib/apt/lists/*cs50*
$ sudo apt-get update
$ sudo apt-get install libcs50
```

**Comment by sasakuvac** [comment]
**$ lsb_release -a**
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial


**$ cat /etc/apt/sources.list**

# deb cdrom:[Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release i386 (20170801)]/ xenial main restricted

# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://ba.archive.ubuntu.com/ubuntu/ xenial main restricted
# deb-src http://ba.archive.ubuntu.com/ubuntu/ xenial main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://ba.archive.ubuntu.com/ubuntu/ xenial-updates main restricted
# deb-src http://ba.archive.ubuntu.com/ubuntu/ xenial-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://ba.archive.ubuntu.com/ubuntu/ xenial universe
# deb-src http://ba.archive.ubuntu.com/ubuntu/ xenial universe
deb http://ba.archive.ubuntu.com/ubuntu/ xenial-updates universe
# deb-src http://ba.archive.ubuntu.com/ubuntu/ xenial-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu 
## team, and may not be under a free licence. Please satisfy yourself as to 
## your rights to use the software. Also, please note that software in 
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://ba.archive.ubuntu.com/ubuntu/ xenial multiverse
# deb-src http://ba.archive.ubuntu.com/ubuntu/ xenial multiverse
deb http://ba.archive.ubuntu.com/ubuntu/ xenial-updates multiverse
# deb-src http://ba.archive.ubuntu.com/ubuntu/ xenial-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb http://ba.archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse
# deb-src http://ba.archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
# deb http://archive.canonical.com/ubuntu xenial partner
# deb-src http://archive.canonical.com/ubuntu xenial partner

deb http://security.ubuntu.com/ubuntu xenial-security main restricted
# deb-src http://security.ubuntu.com/ubuntu xenial-security main restricted
deb http://security.ubuntu.com/ubuntu xenial-security universe
# deb-src http://security.ubuntu.com/ubuntu xenial-security universe
deb http://security.ubuntu.com/ubuntu xenial-security multiverse
# deb-src http://security.ubuntu.com/ubuntu xenial-security multiverse


**$ cat /etc/apt/sources.list.d/cs50-ubuntu-ppa-xenial.list**

deb http://ppa.launchpad.net/cs50/ppa/ubuntu xenial main
# deb-src http://ppa.launchpad.net/cs50/ppa/ubuntu xenial main
# deb-src http://ppa.launchpad.net/cs50/ppa/ubuntu xenial main
# deb-src http://ppa.launchpad.net/cs50/ppa/ubuntu xenial main


**$ sudo rm -rf /var/lib/apt/lists/*cs50***

[sudo] password for sasa: 

**$ sudo apt-get update**

Hit:1 http://ba.archive.ubuntu.com/ubuntu xenial InRelease                     
Hit:2 http://ba.archive.ubuntu.com/ubuntu xenial-updates InRelease             
Get:3 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]     
Hit:4 http://ba.archive.ubuntu.com/ubuntu xenial-backports InRelease           
Get:5 http://ppa.launchpad.net/cs50/ppa/ubuntu xenial InRelease [18,0 kB]      
Get:6 http://security.ubuntu.com/ubuntu xenial-security/main i386 DEP-11 Metadata [60,2 kB]
Get:7 http://security.ubuntu.com/ubuntu xenial-security/main DEP-11 64x64 Icons [57,6 kB]
Get:8 http://security.ubuntu.com/ubuntu xenial-security/universe i386 DEP-11 Metadata [49,6 kB]
Get:9 http://security.ubuntu.com/ubuntu xenial-security/universe DEP-11 64x64 Icons [75,2 kB]
Get:10 http://ppa.launchpad.net/cs50/ppa/ubuntu xenial/main Translation-en [212 B]
Hit:11 https://download.sublimetext.com apt/stable/ InRelease                  
Fetched 363 kB in 3s (98,2 kB/s)
Reading package lists... Done

**$ sudo apt-get install libcs50**

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libcs50

**Comment by kzidane** [comment]
Interesting! Seems `apt` didn't download the `Packages` index file for some reason. What's the output of running the following command?

```
$ ls -la /var/lib/apt/lists/*cs50*
```

**Comment by sasakuvac** [comment]
$ ls -la /var/lib/apt/lists/*cs50*

-rw-r--r-- 1 root root 18036 Sep  9 01:30 /var/lib/apt/lists/ppa.launchpad.net_cs50_ppa_ubuntu_dists_xenial_InRelease
-rw-r--r-- 1 root root   170 Jul 27 20:57 /var/lib/apt/lists/ppa.launchpad.net_cs50_ppa_ubuntu_dists_xenial_main_i18n_Translation-en

**Comment by kzidane** [comment]
Frankly I'm not sure why `apt` doesn't download `Packages` on your system. I've googled but couldn't find similar issues. Have you tried installing from source https://github.com/cs50/libcs50#from-source-linux-and-mac?

**Comment by psiclopz** [comment]
I have the exact same issue, with the exact same behavior.  So it's not just him

**Comment by kzidane** [comment]
@psiclopz have you tried any of the suggested steps above?

**Comment by psiclopz** [comment]
yep, I went through the exact same process.  I ended up just downloading the release and compiling manually.  Just thought you would be interested to know that it isn't isolated.

**Comment by kzidane** [comment]
That's really interesting! Do you happen to have [Team Viewer](https://teamviewer.com/en/download/) installed? If so, do you mind emailing me your Team Viewer ID and password so that I can take a closer look? That would be really helpful. Thank you!

**Comment by psiclopz** [comment]
let me get teamviewer installed on my lubuntu netbook and then I'll shoot you an email so you can see the behavior.  It might be tomorrow.

**Comment by jen-p45** [comment]
Hi, 
I'm having the same problem as well and I was following this along and getting the same output each time. What was the solution? Here is what I was getting from the last two steps -

 :~$ sudo apt-get install libcs50
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libcs50

:~$ ls -la /var/lib/apt/lists/*cs50*
ls: cannot access '/var/lib/apt/lists/*cs50*': No such file or directory

**Comment by RedFlowerTumbleweed** [comment]
Hello!/
I'm having the same problem as well and I was following this along and getting the same output each time. What was the solution? Here is what I was getting from the last two steps -

:~$ sudo apt-get install libcs50
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libcs50

:~$ ls -la /var/lib/apt/lists/cs50
ls: invalid option -- '/'
Try 'ls --help' for more information 


I am running ubuntu
 via a VNC app through my android device.  Could that be the culprit?

**Comment by jen-p45** [comment]
This is all really new to me, and I was trying these steps directly on Ubuntu. When I followed the steps on the class sandbox ( https://ide.cs50.io ) it worked for me. Good luck!

**Comment by saleesh4u** [comment]
Hi what is the solution?

$ sudo apt install libcs50
Reading package lists... Done
Building dependency tree       
Reading state information... Done
**E: Unable to locate package libcs50**

_System:    Kernel: 5.4.0-113-generic x86_64 bits: 64 compiler: gcc v: 9.4.0 
           Desktop: Cinnamon 5.2.7 wm: muffin dm: LightDM Distro: Linux Mint 20.3 Una 
           base: Ubuntu 20.04 focal 
Machine:   Type: Laptop System: Dell product: Inspiron 15-3567_

**Comment by Ikehviky** [comment]
I've read the above step and still, it's not working. Is any solution to this yet?

sudo apt-get install libcs50
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libcs50

**Comment by Ikehviky** [comment]
try this, use the manual method of downloading and extracting. 
this got me rolling 

https://cs50.readthedocs.io/libraries/cs50/c/
