### ISSUE TITLE
Mac make install error: 

### ISSUE THREAD

**Issue by BeatrizElena** [cs50/libcs50#115]
I have the library at /usr/local/libcs50-8.0.5 with 5 items in it: Makefile, README, cs50.0 debian, docs, src, and tests.

I'm at the 'make install' step and getting this message:
rm -rf build debian/docs/ libcs50-* libcs50_*
cc -c -fPIC -std=c99 -Wall -o cs50.o src/cs50.c
error: unable to open output file 'cs50.o': 'Operation not permitted'
1 error generated.
make: *** [build] Error 1

Any ideas on what else I need to do? Thanks!

**Comment by glennlopez** [comment]
I get the same error 

`rm -rf build debian/docs/ libcs50-* libcs50_*
cc -c -fPIC -std=c99 -Wall -o cs50.o src/cs50.c
error: unable to open output file 'cs50.o': 'Operation not permitted'
1 error generated.
make: *** [build] Error 1`

**Comment by kzidane** [comment]
@BeatrizElena @glennlopez can you try cloning the repo instead of downloading the release and see if that fixes the problem? I.e., instead of steps 1 and 2 [here](https://github.com/cs50/libcs50#from-source-linux-and-mac), try running:

```
git clone https://github.com/cs50/libcs50.git
```
and them proceed with the rest of the steps.

**Comment by glennlopez** [comment]
@kzidane 
after git clone https://github.com/cs50/libcs50.git I was forced to the "developer branch" and did the following:

`make install`

yields

> mkdir -p /usr/local/src /usr/local/lib /usr/local/include /usr/local/share/man/man3
cp -r build/* /usr/local
cp: /usr/local/include/cs50.h: Permission denied
cp: /usr/local/lib/libcs50-8.dylib: Permission denied
cp: /usr/local/lib/libcs50-8.1.0.dylib: Permission denied
cp: /usr/local/lib/libcs50.dylib: Permission denied
cp: /usr/local/src/libcs50/cs50.c: Permission denied
cp: /usr/local/src/libcs50/cs50.h: Permission denied
make: *** [install] Error 1

so i tried

`sudo make install`

which yielded:
> mkdir -p /usr/local/src /usr/local/lib /usr/local/include /usr/local/share/man/man3
cp -r build/* /usr/local
cp debian/docs/* /usr/local/share/man/man3

and so I tried to do a "make greedy" for my pset1

`make greedy`
yields the following error

> cc     greedy.c   -o greedy
Undefined symbols for architecture x86_64:
  "_get_float", referenced from:
      _main in greedy-c32b59.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [greedy] Error 1

**Comment by kzidane** [comment]
@glennlopez you need to link with `-lcs50`.

**Comment by glennlopez** [comment]
@kzidane any instructions on how to do this? Sorry, still new to this.
