### ISSUE TITLE
Make Install Error

### ISSUE THREAD

**Issue by man715** [cs50/libcs50#116]
I am not able to use the repository to install since I am using 17.10. 
So, when I attempt to run make install (after running make), I get the following output:
sudo make install
rm -rf build debian/docs/ libcs50-* libcs50_*
cc -c -fPIC -std=c99 -Wall -o cs50.o src/cs50.c
cc -shared -Wl,-soname,libcs50.so.8 -o libcs50.so.8.0.5 cs50.o
rm -f cs50.o
ln -s libcs50.so.8.0.5 libcs50.so.8
ln -s libcs50.so.8 libcs50.so
install -D -m 644 src/cs50.h build/include/cs50.h
mkdir -p build/lib build/src/libcs50
mv libcs50.so* build/lib
cp -r src/* build/src/libcs50
asciidoctor -d manpage -b manpage -D debian/docs/ docs/*.adoc
/bin/sh: 1: asciidoctor: not found
Makefile:34: recipe for target 'docs' failed
make: *** [docs] Error 127

I am not sure how to fix this error. Please help and thank you.

**Comment by kzidane** [comment]
Be sure to install `asciidoctor` per https://github.com/cs50/libcs50#from-source-linux-and-mac!
