### ISSUE TITLE
Ubuntu 17.10 not supported

### ISSUE THREAD

**Issue by Tinytegu** [cs50/libcs50#120]

**Comment by kzidane** [comment]
Did you try installing from source https://github.com/cs50/libcs50#from-source-linux-and-mac?

**Comment by Tinytegu** [comment]
When i type in `make` it says `make: Nothing to be done for 'all'.`

**Comment by Tinytegu** [comment]
Somehow made it work but the `make` command in the terminal doesn't work. have to use `clang`. what can i do to make it work?
