### ISSUE TITLE
get_int error

### ISSUE THREAD

**Issue by shaynemei** [cs50/libcs50#123]
After following the instructions on how to install the library, I sill can't seem to make a simple int.c file to work (following steps as showed in Week1 lecture of CS50). The installation process of the library was fine, no errors, but as i "make int", this pops up.

Undefined symbols for architecture x86_64:
  "_get_int", referenced from:
      _main in int-1cbe38.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [int] Error 1

**Comment by brianyu28** [comment]
Hey @shaynemei, what command are you using to compile `int.c`? Are you definitely linking the CS50 library? i.e. instead of just running:

```
clang -o int int.c
```

be sure to run:

```
clang -o int int.c -lcs50
```

**Comment by shaynemei** [comment]
Hello! I was trying the "make" command. I have tried the clang command as u've demonstrated and it works well.

**Comment by shaynemei** [comment]
Oh but still...
What is the problem? The `clang -o int int.c -lcs50` worked fine tho..

ac:workspace Shayne$ make int -lcs50
cc     int.c   -o int
Undefined symbols for architecture x86_64:
  "_get_int", referenced from:
      _main in int-f466d3.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [int] Error 1

**Comment by peterlxb** [comment]
It works.
thanks

**Comment by leen94** [comment]
Hello,i have a question that i have opened a new file and put this code : 
#include <cs50.h>
#include <stdio.h>

int main(void)
{
    // Prompt user for x
    int x = get_int("x: ");

    // Prompt user for y
    int y = get_int("y: ");

    // Perform arithmetic
    printf("%i plus %i is %i\n", x, y, x + y);
    printf("%i minus %i is %i\n", x, y, x - y);
    printf("%i times %i is %i\n", x, y, x * y);
    printf("%i divided by %i is %i\n", x, y, x / y);
    printf("remainder of %i divided by %i is %i\n", x, y, x % y);
}
after this i wrote clang -o int int.c -lcs50 in the workspace at the bottom, no errors appeared 
but no questions appeared asking me to enter the intergers for example 

please help !
Thank you in advance

**Comment by crossroads1112** [comment]
@leen94 the `clang` command you ran _compiles_ `int.c` into an executable called `int`. In order to run the program you need to run `./int`.

Hope that helps!

PS: Questions like these are really best suited for one of our online forums, such as:

* The [CS50 Facebook Group](https://facebook.com/groups/cs50)
* The [CS50 Stack Exchange](https://cs50.stackexchange.com/)
* The [CS50 subreddit](https://reddit.com/r/cs50)

**Comment by raymondquitua** [comment]
Hi! i don't understand the error i'm getting. please help
**CODE:**
#include <stdio.h>
#include <cs50.h>

int main(void)
{
    printf("Give me an integer:\n");
    int i = get_int()
    printf("You entered: %i\n", i);
}

**ERROR MESSAGE:**
$ make int
clang -fsanitize=signed-integer-overflow -fsanitize=undefined -ggdb3 -O0 -std=c11 -Wall -Werror -Wextra -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wshadow    int.c  -lcrypt -lcs50 -lm -o int
int.c:7:21: error: too few arguments to function call, at least argument 'format' must be specified
    int i = get_int()
            ~~~~~~~ ^
/usr/local/include/cs50.h:87:1: note: 'get_int' declared here
int get_int(const string format, ...) __attribute__((format(printf, 1, 2)));
^
1 error generated.
<builtin>: recipe for target 'int' failed
make: *** [int] Error 1

**Comment by raymondquitua** [comment]
**ERROR_MESSAGE:**

$ make int
clang -fsanitize=signed-integer-overflow -fsanitize=undefined -ggdb3 -O0 -std=c11 -Wall -Werror -Wextra -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wshadow    int.c  -lcrypt -lcs50 -lm -o int
int.c:7:21: error: too few arguments to function call, at least argument 'format' must be specified
    int i = get_int()
            ~~~~~~~ ^
/usr/local/include/cs50.h:87:1: note: 'get_int' declared here
int get_int(const string format, ...) __attribute__((format(printf, 1, 2)));
^
1 error generated.
<builtin>: recipe for target 'int' failed
make: *** [int] Error 1

**Comment by fmagesty** [comment]
> Hey @shaynemei, what command are you using to compile `int.c`? Are you definitely linking the CS50 library? i.e. instead of just running:
> 
> ```
> clang -o int int.c
> ```
> 
> be sure to run:
> 
> ```
> clang -o int int.c -lcs50
> ```

thanks! this solved it for me

**Comment by almagsti** [comment]
hello guys i need help on this one it running on wsl on vs code offline
#include "cs50.h"
#include <stdio.h>

int main(void)
{
    // Prompt user for integers
    int x = get_int("What's x? ");
    int y = get_int("What's y? ");

    // Compare integers
    if (x < y)
    {
        printf("x is less than y\n");
    }
    else if (x > y)
    {
        printf("x is greater than y\n");
    }
    else if (x==y)
    {
        printf("x is equal to y\n");
    }
} 
it shows this error
/usr/bin/ld: /tmp/cctCWsYE.o: in function `main':
hello.c:(.text+0x18): undefined reference to `get_int'
/usr/bin/ld: hello.c:(.text+0x2f): undefined reference to `get_int'
collect2: error: ld returned 1 exit status
