### ISSUE TITLE
Windows instillation 

### ISSUE THREAD

**Issue by aimalamiri** [cs50/libcs50#124]
How to install CS50 lib in windows ?

**Comment by CatchMeFastFat** [comment]
what is your DE ?

you can use mysys2 and use the same instruction as linux.

cd library50-c-5
gcc -c -ggdb -std=c99 cs50.c -o cs50.o
ar rcs libcs50.a cs50.o

better: use docker with ubunuto and shared file.

**Comment by aimalamiri** [comment]
I'm using Visual studio 2012 ultimate in windows 10 32bit and I'm not able to install VM to use Ubuntu so if there is a better solution then please help me .

**Comment by CatchMeFastFat** [comment]
simple answer just use 2 files `cs50.c ` `cs50.h ` to your project in visual studio "source & header".

**Comment by Lishkon** [comment]
@CatchMeFastFat don't you know by chance how can this be done on cLion as well?

**Comment by CatchMeFastFat** [comment]
@Lishkon if you are using CMAKE with clion: add cs50.c this to cmakefile.txt, assuming that your project have inc and src directories. 

```cmake
set(APP_NAME foo)
project(APP_NAME C)
set(SOURCE_ROOT ${CMAKE_SOURCE_DIR})

include_directories(
  "path/to/cs50.h/directory"
  ${SOURCE_ROOT}/inc
  )

file(GLOB SOURCE_GLOB
  "path/to/cs50.c"
  ${SOURCE_ROOT}/src/*.c
  )

set(SOURCE_FILES
  ${SOURCE_GLOB}
  )

set(CMAKE_C_FLAGS "-O0 ...")

add_executable(${APP_NAME} ${SOURCE_FILES} )


```

**Comment by reconix23** [comment]
# 14 Jan 2020 STATUS: not fixed.
