### ISSUE TITLE
Recipe for target "" failed

### ISSUE THREAD

**Issue by devlwkyan** [cs50/libcs50#141]
I can compile it successfully, however when I try to run it, I have the following output:

![image](https://user-images.githubusercontent.com/20567733/47362926-fac89080-d6ab-11e8-898d-0f75476b7278.png)

I've installed it through Ubuntu apt and I'm using Clion IDE.

*I'd tried installing it manually (including using 'DESTDIR'=/usr/local/), however I've got the same error.
*I'm using POP_os, which is based on Ubuntu 18.04 LTS

**Comment by dmalan** [comment]
Looks like you'll need to configure CLion to link against `libcs50`. Not familiar with the process personally, but perhaps one of the below will help?

* https://intellij-support.jetbrains.com/hc/en-us/articles/206558149-How-do-I-add-my-libraries-to-the-project-
* https://stackoverflow.com/a/50366664/5156190 are on point?
* https://cmake.org/cmake/help/latest/command/target_link_libraries.html
