### ISSUE TITLE
Broken reference code snippet

### ISSUE THREAD

**Issue by abranhe** [cs50/libcs50#145]
I was looking over [reference.cs50.net](https://reference.cs50.net) and I found that the example for the `strtoll()` function was all over the place probably because they used (`) instead of (```) on markdown file. 

I was trying to see if the reference was an open source repository but I couldn't find it so I am opening an issue here, but is is not related at all with this project. Please fix that :)

Check it out: https://reference.cs50.net/stdlib/strtoll

[<img width="1392" alt="strtoll" src="https://user-images.githubusercontent.com/21347264/48288288-9a6e7880-e439-11e8-9ff0-83d4e1ccbdee.png">](https://reference.cs50.net/stdlib/strtoll)

**Comment by Sebbyastian** [comment]
lol... don't use CS50 as a reference manual for C programming.

If you scroll down and click "CONFORMING TO" in this "reference" you'll see a list of standards that these manual pages _should_ conform to (but kinda don't, sometimes)...

For example, you've got POSIX.1-2001 and POSIX.1-2008... well, let us not work with resources so out-of-date... [here is POSIX.1-2017](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strtoll.html).

You've also got [C99](http://port70.net/~nsz/c/c99/n1256.html#7.20.1.4) and [C11](http://port70.net/~nsz/c/c99/n1256.html#7.22.1.4) in that list.

I advise against using these references/tutorials to learn C.

**Comment by abranhe** [comment]
@Sebbyastian I am not talking using this reference or not, I am creating the issue for them to fix the docs!

**Comment by abranhe** [comment]
It looks that it’s already fixed, with a new website, therefore I am closing the issue!
