### ISSUE TITLE
Makefile with inconsistent library name (VERSION vs. MAJOR)

### ISSUE THREAD

**Issue by Blauelf** [cs50/libcs50#146]
In the [Makefile of 8.1.2](https://github.com/cs50/libcs50/blob/33100fb483531f077642274a9055e593d4870a8d/Makefile#L35-L41), there's

```
$(LIBS): $(SRC) $(INCLUDE) Makefile
	$(CC) $(CFLAGS) -fPIC -shared $(LINKER_FLAGS) -o $(LIB_VERSION) $(SRC)
	ln -sf $(LIB_MAJOR) $(LIB_BASE)
	mkdir -p $(addprefix build/, include lib src)
	install -m 644 $(SRC) build/src
	install -m 644 $(INCLUDE) build/include
	mv $(LIB_VERSION) $(LIB_BASE) build/lib
```
If I read it correctly, this builds `$(LIB_VERSION)`, but in the next step creates a link to `$(LIB_MAJOR)` (which wasn't built in the step before).

**Comment by kzidane** [comment]
@Blauelf `$(LIB_MAJOR)` should be automatically created by `ldconfig` when you `make install`.

**Comment by Blauelf** [comment]
Not sure if I just don't understand makefiles correctly, but does `$(LIB_MAJOR)` exist at the time this command is run, and even if I start `make` without any compiled files?

**Comment by Blauelf** [comment]
Oh, apparently, I am misunderstanding symbolic links. They work fine even if the target does not exist.

Still, there is a target `/build/lib/$(LIB_MAJOR)` that is not created in that step, is that the way it is meant?

**Comment by kzidane** [comment]
@Blauelf yes, unless you're doing a `make install`, you shouldn't be using `$(LIB_MAJOR)` directly.

**Comment by Blauelf** [comment]
But `ldconfig` does not seem to create that one. After a `make install`, I get two files in `/usr/local/lib/`:
```
-rwxr-xr-x 1 root root 21736 Nov 20 23:44 libcs50.so.8.1.2
lrwxrwxrwx 1 root root    12 Nov 20 23:44 libcs50.so -> libcs50.so.8
```
The link `libcs50.so.8 -> libcs50.so.8.1.2` is missing.

**Comment by kzidane** [comment]
Hmm, which Linux distro are you using? Does it work if you do `ldconfig /usr/local/lib`?

**Comment by Blauelf** [comment]
Tried on arch linux. And yes, that last version with path works, creating the link. Seems like that linux distro does not list `/usr/local/lib` in `/etc/ld.so.conf.d/*` or `$LD_LIBRARY_PATH`, meaning neither linking nor execution works out of the box.

**Comment by kzidane** [comment]
I see. I'm gonna fix shortly. Thank you!

**Comment by Blauelf** [comment]
I think it's more an issue with arch Linux discouraging usage of `/usr/local`. Not sure why they do. So to use the library when it is installed in `/usr/local/lib`, the user always has to adjust something on their system, even if it installed there properly.

**Comment by crossroads1112** [comment]
Apologies for the delayed response, I just saw this. This is what `DESTDIR` is for in the Makefile. If you run `sudo DESTDIR=/usr/lib make install`, it will install into `/usr/lib`. It may make sense to make `/usr/lib` be the default on linux.

**Comment by kzidane** [comment]
#147

**Comment by Blauelf** [comment]
Thanks both of you for all that information.
