### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Sohanur-2005** [cs50/libcs50#156]
sohanur@sohanur-workstation:~/Programming/C/App (II)$ clang main.c
/usr/bin/ld: /tmp/main-b96858.o: in function `main':
main.c:(.text+0x20): undefined reference to `get_string'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by curiouskiwi** [comment]
When using the CS50 library, be sure to link it with the `-lcs50` clang argument:  `clang -lcs50 main.c`
