### ISSUE TITLE
You've still got memory leaks?

### ISSUE THREAD

**Issue by Sebbyastian** [cs50/libcs50#159]
What I will say about this uhh... kind of complex a memory leak is that kind of thought process is probably not a good idea for students who you want to teach to think outside of the box and criticise their own code. I've said all of this before, but let's quickly recap before I get onto something which you probably want more of.

> ... In the strictest sense, "leaking" is so abstract as to be unpreventable. It's quite trivial to initialize a collection at the start of a program, fill it with tons of objects with destructors, and then enter an infinite event loop that never refers to it. The collection will sit around uselessly, holding on to its precious resources until the program terminates (at which point all those resources would have been reclaimed by the OS anyway).

... much like the libcs50 code did, when it would read input... Don't get me wrong; I came here hoping you don't still use that technique, that maybe, just maybe, you would revisit this thought process at a later date. While a library is not *exactly* unsuitable for the task of garbage collection, the task itself when done properly requires some automatic inspection of data structures, and I think it might pay to investigate those options further (see how `valgrind` debugs code, maybe try to retrofit some of that stuff, because it seems like valgrind picks up leaks *on time* for a garbage collector)...

What happens when you allocate memory for a resource, use it *once*, hold on to it until the end of the program *and then do one of the following*?

 - maybe you leave the clean-up entirely to the OS... some people actually do claim the OS will clean up for them. That's a good one... worth a chuckle, huh? I'm sure we've all *blatantly* leaked an object here or there. Some people try to say this is not a leak because the OS cleans up when the program terminates... these people are good comedians!
 - maybe you call `free` on every object at the last possible point in time, in which case not only did you keep reserved all of that memory for no good reason for the duration of the program (which is the problem with leaks anyway) but you also managed to suppress the tool that would warn you about this kind of problem... at the same time you get the same overhead as someone who uses `realloc`+`free` *correctly*, but at the worst time! See, your *first-pointer* has a point here, the OS will typically free up your resources faster *at this useless point in time* if you just leave it to terminate... it's *still a leak*, at least *conceptually*, though the leak warnings are suppressed, and I actually think that's a shame.

In fact, I'm going to label this not as a bug but an optimisation improvement (edit: turns out I can't do that): remove all of the `teardown` code, your code will run faster AND you'll get the opportunity to introduce `valgrind`... no seriously, though, I am writing something which is intended towards educational learning and proving code so we have some overlap in places. I am legitimately stumped as to why you'd suppress this, as it presents a great optimisation effort and also, all of that `teardown` stuff is really heavily implementation-defined (and slow, and performed at the last possible minute, as previously mentioned, effectively spoiling the point).

Here's another one, maybe a more legitimate performance hint:

```
void *realloc_power(void *list, size_t index, size_t size)
{ return index & (index + 1)      ? list
	   : SIZE_MAX / size <= index ? NULL
                                  : realloc(list, (2 * index + 1) * size);
}
```

Dress it up and format it as you like; I just copy/pasta from one of my local projects. It's not meant to be a direct replacement for `realloc`, rather a wrapper that facilitates fast, type-generic stacks... or at least, that's what I wrote it for. You'll probably get better use out of it, though, because I like to think what I was going to use it for can just be a direct file/stream operation in my projects... where there's a will, there will be a way.

You have an extra `capacity` variable laying around which you don't need if you use this kind of logic. Additionally, if you're only pushing and popping elements off like your string is a FIFO stack, as you kind of do whilst maintaining the allocation, then it is far better to allocate by a power of two minus one, so as to reduce unnecessary calls to `realloc` (which results in context switches between userland and kernel, etc)... so you get to remove a variable and you get to allocate larger chunks with less context switches.

At line cs50.c#L133 to L154 you have the somewhat equivalent logic baked into your *read character into a stack-kinda-thing*, though your logic is `realloc`ing every `char` which is going to take a hit. You can keep `size` or `capacity`, either or, but you don't need both, thanks to the magic of powers of two. I'll remove the `capacity` in my example usage below:

```
    // I'm not sure how you feel about `fgetc` but I think you'll agree it's very easy to abuse
    // while ((c = fgetc(stdin)) != '\r' && c != '\n' && c != EOF)

    // where-as `fread` keeps the `EOF` indicator separate from the character values...
    char c; // just an observation I think helps avoid various common pitfalls for some students...
    while (fread(&c, 1, 1, stdin) == 1 && strchr("\r\n", c) != NULL)
    {
        string temp = realloc_power(buffer, size, sizeof *temp);
        if (temp == NULL)
        {
            free(buffer);
            return NULL;
        }
        buffer = temp;

        // Append current character to buffer
        buffer[size++] = c;
    }
```

Additionally, you could use this to create a growing array of `int` in future lessons... or a growing array of `char *`, which I note you create below it *so long as* (and this is important) the size of your collection grows (or shrinks) by exactly one item per insertion...

I can't help but wonder why it is you would want to "Minimize buffer" of an array which you're *only growing by one element per `realloc` call*, but if nothing else changes this might be some food for thought. The single byte which you might have a chance at "minimizing" currently seems outweighed by the length and bottleneck of the machine code generated in order to perform the "minimizing". Usually I wouldn't bother pointing this out, but it's *one byte*!

I suppose it makes sense when you're allocating by a power of two like this suggestion here, right? Then after reading the string, you want to shed *all of that unused allocation weight*... that weight which at the moment I think is only *one character*. I think (just a guess) that I am being generous to call that *minimization process* an optimisation to begin with, when you consider that you're asking *some* systems to *find a new chunk of memory, copy the contents of the memory over, free the old chunk and return the new*... and *all of that just to reduce memory use by one byte*.

I get that we should value some resource not so much for its efficiency but also the design patterns it promotes, as an educational resource... see how this function also works for other types below, in other similar places you've used `realloc`:

```
    string *tmp = realloc_power(strings, allocations, sizeof (string));
    if (tmp == NULL)
    {
        free(s);
        return NULL;
    }
    strings = tmp;

    // Append string to array
    strings[allocations++] = s;
```

In that sense `realloc_power` is a type-generic kind of helper function for your exact usecase. As you can see, you'd be calling `realloc` (and thus having to context shift between userland and kernel) much less for *that* code, too. There's a performance enhancement in multiple places that also enhances source code value (by being modular and reusable, perhaps even in industry code, providing we take care), right?

Well, I say that, and then I might very well find in some years time this code has some wrapper on top of it that causes the input counter to double only every time the wrapper thinks it ne-- ohh... let's just not go there hehe. Crap's too easy to abuse in C.

**Comment by Sebbyastian** [comment]
What might perhaps be most beneficial is a function-like macro which offers hints at your *garbage collector*, allowing it to free up some memory manually, *before* program termination. The macro could also assign the variable to `NULL` to prevent double-frees... and if this is all you do, congratulations, you have just invented the worlds most complex `realloc` wrapper. hehe, I can't judge for that.

**Comment by dmalan** [comment]
Thank you for the thoughtful note, but the CS50 Library is intended to be an abstraction atop otherwise pointer-based and error-prone I/O functions. Any performance overhead is negligible in the contexts in which the library is intended to be used. And the library indeed garbage-collects itself so that, if students' code is run through tools like `valgrind`, we can detect any memory leaks in their own code as opposed to ours.

**Comment by Sebbyastian** [comment]
> Any performance overhead is negligible in the contexts in which the library is intended to be used.

To be clear here, the performance overhead is rather significant. I think you might be brushing it aside... -shrugs- it's not my job to pull heads out of sand

> the library indeed garbage-collects itself

... for whatever meaning of *"garbage-collects"* you are referring to... where-by you occupy the resources for the entirety of the program life (right up until the end), even though you don't need to occupy those resources, this is not *"garbage collection"*. You know this. This is *a memory leak*. Whether valgrind picks it up or not, it is a memory leak. I've already gone there, you don't want my help, very well...

> we can detect any memory leaks in their own code as opposed to ours.

You could of course prefer the option of not setting a good example... and then your students will be more likely to leak memory in the same way you do.
