### ISSUE TITLE
Compiling cs50.h invokes undefined behavior because of _CS50_H

### ISSUE THREAD

**Issue by rillig** [cs50/libcs50#162]
C99 says in 7.1.3 item 1:

> All identifiers that begin with an underscore and either an uppercase letter or another underscore are always reserved for any use.

`cs50.h` uses such an identifier (`_CS50_H`) as a multiple-inclusion guard. Since this header file is used in teaching, it must be exemplary. Invoking undefined behavior is not exemplary.

**Comment by dmalan** [comment]
Good catch, thanks!
