### ISSUE TITLE
`get_long_long` deprecated; "credit" exercise requires revision

### ISSUE THREAD

**Issue by Sebbyastian** [cs50/libcs50#169]
There is a section of this exercise that suggests using `get_long_long`... I think removing that would make sense, otherwise you need to reintroduce `get_long_long` to the library again.

**Comment by curiouskiwi** [comment]
The current version of the problem (https://lab.cs50.io/cs50/labs/2019/x/credit/) explicitly mentions `get_long` in several places.  Perhaps you are following an outdated spec?   Can you post a link to a current document that still suggests `get_long_long`?

**Comment by dlloyd09** [comment]
Per @curiouskiwi, I agree that there doesn't appear to be a currently-active CS50 problem that uses `get_long_long`. Some archive versions of Credit do, but the library is not intended to be backwards-compatible with all prior problems. Please do let us know if there is an active (2019) problem that explicitly mentions `get_long_long`, though!

**Comment by Sebbyastian** [comment]
Ah, in that case, is the course also supposed to function on Windows, where
LONG_MAX typically isn't large enough to store a credit card number?

If so, then you'll probably need get_long_long again...

If not, then I wonder what the deal with line 420 of cs50.h is (<
https://github.com/cs50/libcs50/blob/develop/src/cs50.c#L420>)...
