### ISSUE TITLE
Add support for old style get_string()

### ISSUE THREAD

**Issue by Islam0mar** [cs50/libcs50#170]
I just updated libcs50 and found that old style doesn't work which was to `printf` before `get_string()`.

`get_string` macro doesn't support empty  arguments!

I use the following [macro][1] before my functions to support the old style:

```C
#undef get_string
#define FIRST(...) FIRST_I(__VA_ARGS__)
#define FIRST_I(a, ...) a
#define COMMA_IF_PARENS(...) ,get_string0()
#define IS_EMPTY(...) COMMA_IF_PARENS __VA_ARGS__()
#define RM_FIRST(...) RM_FIRST_I(__VA_ARGS__)
#define RM_FIRST_I(x, ...) __VA_ARGS__
#define CHOOSE_FUNC(...) \
  SECOND(IS_EMPTY(FIRST(__VA_ARGS__)), get_stringn(__VA_ARGS__))
#define SECOND(...) FIRST(RM_FIRST(__VA_ARGS__))
#define get_string0() get_string(NULL, NULL)
#define get_stringn(...) get_string(NULL, __VA_ARGS__)
#define get_string(...) CHOOSE_FUNC(__VA_ARGS__)
```

- Would you support compiling get_string()?

[1]: https://stackoverflow.com/questions/57123398/c-preprocessor-macro-doesnt-parse-comma-separated-tokens/57125670#57125670

**Comment by dmalan** [comment]
Hi @Islam0mar, what's the use case precisely? We haven't taught the argument-less `get_string()` form in CS50 for a few years now.

**Comment by Islam0mar** [comment]
Hi, I took this course 4-5 years ago through edx and it was the best course I have ever took. There is no other courses which provide such motivation -especially first two lectures- and open other fields like that, so I wanted to express my gratitude for your teaching style.

I used to `printf... get_string()` --I use it for my personal code---, but I understand that you are adapting python style.

I will close it as it isn't relevant to the course material and I can use the above macro to compile.

regards

**Comment by dmalan** [comment]
Thanks for the kind words! 

We considered supporting calling conventions like

1. `get_string("String: ")`,
1. `get_string("")`, and
1. `get_string()`,

but the last (implemented with a macro, as you note), which effectively made the argument optional, wasn't very C-like, so we phased it out over a few years!
