### ISSUE TITLE
Can't Install libcs50 in Ubuntu 19.04

### ISSUE THREAD

**Issue by teekamsuthar** [cs50/libcs50#182]
`$ curl -s https://packagecloud.io/install/repositories/cs50/repo/script.deb.sh | sudo bash`

Detected operating system as Ubuntu/disco.
Checking for `curl...`
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/cs50_repo.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

`$ sudo apt install libcs50`
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libcs50

**### How do I manually install cs50.h ?**

**Comment by kzidane** [comment]
Try `sudo apt-get update` once more then `sudo apt-get install libcs50`!
