### ISSUE TITLE
Add documentation for CMakeLists.txt on macOS (probably also Linux)

### ISSUE THREAD

**Issue by techouse** [cs50/libcs50#190]
Hey!

I just spent the better part of an hour trying to figure out how to make this work with an IDE (namely CLion) that uses CMake in conjunction with `CMakeLists.txt`. Eventually I did figure it out and it works like a charm 😇 Still, could you please add this info for future reference?

If you are on macOS, make sure your `CMakeLists.txt` looks something like this and reload your CMake project.

This `CMakeLists.txt` assumes your script is called `what_is_your_name.c`. **DON'T** just copy & paste it!
```cmake
cmake_minimum_required(VERSION 3.15)
project(what_is_your_name C)

include_directories(/usr/local/include)  # <-- add this to include header files 
link_directories(/usr/local/lib)  # <-- add this to link libraries

set(CMAKE_C_STANDARD 99)

add_executable(what_is_your_name what_is_your_name.c)
target_link_libraries(what_is_your_name cs50)  # <-- add this line to link with the cs50 library
```

**Comment by HazemNoor** [comment]
Thanks @techouse Klemen

**Comment by dEhiN** [comment]
Do you guys think the CMakeLists.txt file could be modified for Windows?

**Comment by techouse** [comment]
Probably yes. You'd have to play with the `include_directories` and  `link_directories` settings.

> Do you guys think the CMakeLists.txt file could be modified for Windows?

**Comment by DigitalSavior** [comment]
Thank you so much! This has been driving me nuts.
