### ISSUE TITLE
Compile and use libcs50 on Windows

### ISSUE THREAD

**Issue by dEhiN** [cs50/libcs50#193]
Could you add steps in the Readme for compiling and using libcs50 on Windows? I'm running Windows 10 and using VS Code with the MinGW gcc compiler. I have Debian set up using WSL, so I know that I could follow the steps for compiling libcs50 using the WSL enviroment. But I'm pretty sure that would just allow me to use libcs50 in the WSL Debian enviroment. I also know that VS Code has a Remote-WSL extension, but do I really need to always go through a *nix environment just to utilize libcs50? Is there a way to compile and use libcs50 natively on Windows? Thanks.

**Comment by AbhigyanKumar** [comment]
**Yes**, if you have **_Windows Subsystem_ for _Linux**_ installed on your Windows device.

**Comment by uselessscat** [comment]
I'd like to use windows without the linux subsystem. I have some background in programming so i use visual studio to debug some C code. Visual studio has a lot of tools to debug a C program. I can view the assembler code that the compiler generates, the memory in realtime, stacktrace, variable inspector, inmediate commands (like an repl for c), the ability to set breakpoints... 

Here is the debbuging session of a problem in cs50 that im trying to resolve.

![image](https://user-images.githubusercontent.com/15332878/93008934-2c250080-f551-11ea-9904-3ee73bd48fbd.png)

Is there a way to get these tools in Cloud9 Ide or linux?

**Comment by Rubix982** [comment]
@uselessscat , one way, I think, is to go into the settings for the project you made for your C program, and link the two files in the `linking` option somewhere. I remember I did something similar with an assembly library an year ago. Basically, all it would do is go through the files you linked and configure itself accordingly.

**Comment by timeneverdie** [comment]
https://github.com/cs50/libcs50/issues/189#issuecomment-737173845

My full solution for VSCode on Windows. Step by step inside.

**Comment by mohitk30** [comment]
hi ,i would like to work  on this issue ca you suggest me ways to get started ?

**Comment by Rubix982** [comment]
Hi, @mohitk30 . Please look into topics for C/C++ such as,

I think it's better you use WSL at the moment, but if you would like to, then please take a look at the below topics,

1. Linking
2. Building with multiple *.c/cpp files
3. Integrating with a Windows IDE or Text Editor, i.e., Notepad++, Visual Studio, Visual Studio Code ..., etc, to serve as a guide for new servers that happen to stumble upon this issue

In general, see what it takes to compile multiple sources and header files together in Windows, and how you can write or prepare a step-by-step guide for folks who might want to try it out as well.

Good luck!

**Comment by MADEPADIO** [comment]
Personally, I'll advise you to take @timeneverdie's solution. 

I also made some modifications to it too.

**Comment by MADEPADIO** [comment]
> Personally, I'll advise you to take @timeneverdie's solution.
> 
> I also made some modifications to it too.

My reason for saying this is because as difficult as it may seem, every programming language must be able to function properly using the various terminals for the various OSs before IDEs are talked about. 

Although you can go for what will be a lot more conducive

**Comment by MADEPADIO** [comment]
Hi, I just went through your solution and I was impressed plus I appreciate
the fact that you also reached out to me.

Sadly, I haven't been written my own story of how I was able to fix mine
but I'll email you as soon as I do. But to be clear, I have a working
*libcs50*, and it works on PowerShell and cmd so far. Plus, it also works
on Vscode and I must say, I dread going through the process again because
it's only fun when you get it right. 😅
I promise to email you the link when I post the procedures I took and I'll
also share your link for others that want to try.

**Comment by MADEPADIO** [comment]
I forgot to add:
    Could you please add a new comment under your solution, explaining and
narrating each step taken to solve this issue? Please do not take it the
wrong way, I'm only requesting you simplify it for other readers.

Thank you.

**Comment by yashpalgoyal1304** [comment]
hi, thanks for appreciations

> add a new comment under your solution, explaining and narrating each step taken to solve this issue

as much as i'd like to explain what each step means, bt i cant. as the answer in its current state as of now is already so long as it is, and adding more verbosity will only add length to it and many will not read that then.

the second reason for not adding the details is that most all the details i ommitted are given in the previous answers there.

**Comment by MarianoBobadilla** [comment]
Hola como estamos, estoy iniciando el curso de Base de Datos (luego iré haciendo los demás)  y necesito practicar los ejercicios y entregar las tareas de SQLite, como me contecto a la Terminal? alguna guia? Desde ya muchas gracias...

**Comment by dEhiN** [comment]
> Hola como estamos, estoy iniciando el curso de Base de Datos (luego iré haciendo los demás) y necesito practicar los ejercicios y entregar las tareas de SQLite, como me contecto a la Terminal? alguna guia? Desde ya muchas gracias...

Hola y bienvenido. A cual Terminal quiere usted se conectar? El Windows Terminal en su computador o a un terminal de CS50 Codespace o a un otro?
