### ISSUE TITLE
eprintf still has references everywhere

### ISSUE THREAD

**Issue by TheRijn** [cs50/libcs50#195]
`eprintf` doesn't exists anymore, but is still in the tests and the README.

**Comment by kzidane** [comment]
Not in the latest version of the library. Where do you see it exactly?

**Comment by TheRijn** [comment]
Here https://github.com/cs50/libcs50/blob/develop/tests/eprintf.c
And in the readme https://github.com/cs50/libcs50#documentation

**Comment by kzidane** [comment]
Ah, thanks! Removed via d53d55c.
