### ISSUE TITLE
Sandbox doesnt work on TOR or Epiphany

### ISSUE THREAD

**Issue by sk-alexis** [cs50/libcs50#197]
The cs50 sandbox has a problem when using TOR or Epiphany, 2 major browsers on the Unix world.

The terminal window on the bottom works but doesnt print the characters therefore making it impossible to use it.

**Comment by dmalan** [comment]
Afraid the underlying cloud provider only supports these!

* Google Chrome
* Mozilla Firefox
* Microsoft Edge
* Safari

**Comment by sk-alexis** [comment]
Would that something you would consider supporting in the future. I believe this is related to a javascript issues. Being that this is a CS related course and many developers use TOR or Ephyphany browsers.?

**Comment by dmalan** [comment]
Afraid that's an implementation detail beyond our control right now!

**Comment by sk-alexis** [comment]
sounds good if I find a solution I will make a pull request. Cheers

**Comment by sk-alexis** [comment]
@dmalan this issue as been resolved recently with use of cloud9 services from aws, so probably should be deleted. cheers
