### ISSUE TITLE
Hey guys i am new to code and I got an error and I dont know what to do

### ISSUE THREAD

**Issue by dracula0** [cs50/libcs50#200]
The error is :
Error

main.lua:22: module 'push' not found:
no field package.preload['push']
no 'push' in LOVE game directories.
no file 'push' in LOVE paths.
no file '.\push.lua'
no file 'C:\Program Files\LOVE\lua\push.lua'
no file 'C:\Program Files\LOVE\lua\push\init.lua'
no file '.\push.dll'
no file 'C:\Program Files\LOVE\push.dll'
no file 'C:\Program Files\LOVE\loadall.dll'

Traceback

[C]: in function 'require'
main.lua:22: in main chunk
[C]: in function 'require'
[C]: in function 'xpcall'
[C]: in function 'xpcall'

I wrote the code:

WINDOW_HEITH = 720
WINDOW_WIDTH = 1280

function love.load()
	love.window.setMode(WINDOW_WIDTH, WINDOW_HEITH,{
		fullscreen = false,
		resizable = false,
		vsync = true
	})
WINDOW_HEITH = 720

end

function  love.draw()
	love.graphics.printf("Hello Pong", 0, WINDOW_HEITH / 2 - 6,
		WINDOW_WIDTH, "center")

end

push = require "push"

WINDOW_WIDTH = 1280
VIRTUAL_WIDTH = 432
VIRTUAL_HEITH = 243

function love.load()
	push:setupScreen(VIRTUAL_WIDTH, VIRTUAL_HEIGHT, WINDOW_WIDTH, WINDOW_HEITH, {
		fullscreen = false,
		resizable = false,
		vsync = true
	})
end

**Comment by dmalan** [comment]
Afraid this isn't an issue for this repo! See https://cs50.harvard.edu/x/ed!
