### ISSUE TITLE
'get_long' function not working

### ISSUE THREAD

**Issue by lucas404x** [cs50/libcs50#201]
Hi guys. So, I tried to run my solution on my computer.
I installed the lib cs50 in my OS (Ubuntu 18.04) through the curl tool.

But when I went to compiler my program, I received this error in terminal:

`/tmp/cc2gMN9Z.o: In function 'main':
credit.c:(.text+0x15): undefined reference to 'get_long'
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'credit' failed
make: *** [credit] Error 1
`

Someone could help me, please?

**Comment by Rubix982** [comment]
Hi @lucas404x !
Can you let us know what command you sued to compile the program?
In my case, I would do something like
```
gcc test.c -lcs50 -o test
```

Where `gcc` is my compiler, `test.c` is my source file which has `#include <cs50.h>`, and `test`, the name of the file being generated for me to run.

**Comment by lucas404x** [comment]
Hi @Rubix982 !

Thank you very much! It working. =)

**Comment by Rubix982** [comment]
That's great!
Please let me know if you understand what -lcs50 does, and if you need any pointers to understand what it means.
If not, that's great! Best of luck for the future.

**Comment by seanderue** [comment]
I appreciate your answer @Rubix982, it helped me too. Would you mind helping me understand what -lcs50 does?

**Comment by eltonMoraisD** [comment]
@Rubix982 thaks a lot
