### ISSUE TITLE
E: Unable to locate package libcs50 in ubuntu

### ISSUE THREAD

**Issue by mazenalimad** [cs50/libcs50#202]
This is Ubuntu desktop version for Windows 10
I don't know why this problem appears and I searched for hours and didn't find a solution to it

`~$ sudo apt install libcs50
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libcs50`
.....................................................................................................................................................................................................
The copy information I own

~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
......................................................................................................................................................................................................

![22222222](https://user-images.githubusercontent.com/55521385/80682718-b3eefe80-8acb-11ea-92eb-4e0c1cdc3474.PNG)

**Comment by Rubix982** [comment]
Isn't the command for installing libcs50 `sudo apt-get install libcs50` , it's under Installation -> Ubuntu .

**Comment by dmalan** [comment]
@mazenalimad, sure you've installed the repo?

https://github.com/cs50/libcs50#ubuntu

**Comment by kzidane** [comment]
Just released for focal actually. Try:

```
sudo apt update && sudo apt install -y libcs50
```

**Comment by mazenalimad** [comment]
@kzidane 
`~$ sudo apt update && sudo apt install -y libcs50
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease [106 kB]
Hit:3 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Get:4 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [31.7 kB]
Get:5 http://archive.ubuntu.com/ubuntu focal-updates/main Translation-en [13.7 kB]
Get:6 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 c-n-f Metadata [1208 B]
Get:7 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [12.3 kB]
Get:8 http://archive.ubuntu.com/ubuntu focal-updates/universe Translation-en [5676 B]
Get:9 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 c-n-f Metadata [788 B]
Get:10 http://security.ubuntu.com/ubuntu focal-security InRelease [107 kB]
Ign:11 http://ppa.launchpad.net/cs50/ppa/ubuntu focal InRelease
Err:12 http://ppa.launchpad.net/cs50/ppa/ubuntu focal Release
  404  Not Found [IP: 2001:67c:1560:8008::15 80]
Get:14 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [25.9 kB]
Get:15 http://security.ubuntu.com/ubuntu focal-security/main Translation-en [11.2 kB]
Get:16 http://security.ubuntu.com/ubuntu focal-security/main amd64 c-n-f Metadata [928 B]
Get:17 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [3576 B]
Get:18 http://security.ubuntu.com/ubuntu focal-security/universe Translation-en [3328 B]
Get:19 http://security.ubuntu.com/ubuntu focal-security/universe amd64 c-n-f Metadata [492 B]
Get:13 https://packagecloud.io/cs50/repo/ubuntu focal InRelease [23.2 kB]
Err:13 https://packagecloud.io/cs50/repo/ubuntu focal InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 695BD8926FB7A037
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/cs50/ppa/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://packagecloud.io/cs50/repo/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 695BD8926FB7A037
E: The repository 'https://packagecloud.io/cs50/repo/ubuntu focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.`

**Comment by mazenalimad** [comment]
@kzidane 

> ~$ sudo apt update && sudo apt install -y libcs50
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease [106 kB]
Hit:3 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Get:4 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [31.7 kB]
Get:5 http://archive.ubuntu.com/ubuntu focal-updates/main Translation-en [13.7 kB]
Get:6 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 c-n-f Metadata [1208 B]
Get:7 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [12.3 kB]
Get:8 http://archive.ubuntu.com/ubuntu focal-updates/universe Translation-en [5676 B]
Get:9 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 c-n-f Metadata [788 B]
Get:10 http://security.ubuntu.com/ubuntu focal-security InRelease [107 kB]
Ign:11 http://ppa.launchpad.net/cs50/ppa/ubuntu focal InRelease
Err:12 http://ppa.launchpad.net/cs50/ppa/ubuntu focal Release
  404  Not Found [IP: 2001:67c:1560:8008::15 80]
Get:14 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [25.9 kB]
Get:15 http://security.ubuntu.com/ubuntu focal-security/main Translation-en [11.2 kB]
Get:16 http://security.ubuntu.com/ubuntu focal-security/main amd64 c-n-f Metadata [928 B]
Get:17 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [3576 B]
Get:18 http://security.ubuntu.com/ubuntu focal-security/universe Translation-en [3328 B]
Get:19 http://security.ubuntu.com/ubuntu focal-security/universe amd64 c-n-f Metadata [492 B]
Get:13 https://packagecloud.io/cs50/repo/ubuntu focal InRelease [23.2 kB]
Err:13 https://packagecloud.io/cs50/repo/ubuntu focal InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 695BD8926FB7A037
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/cs50/ppa/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://packagecloud.io/cs50/repo/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 695BD8926FB7A037
E: The repository 'https://packagecloud.io/cs50/repo/ubuntu focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by mazenalimad** [comment]
@dmalan Yes, I followed the instructions, he was saying I can download the package
but today

>  ~$ curl -s https://packagecloud.io/install/repositories/cs50/script.deb.sh | sudo bash
bash: line 1: syntax error near unexpected token `newline'
bash: line 1: `<!DOCTYPE html>'

**Comment by kzidane** [comment]
@mazenalimad try reinstalling the repo and try again?

**Comment by kzidane** [comment]
Alternatively, try adding the key again:

```
curl -L https://packagecloud.io/cs50/repo/gpgkey | sudo apt-key add -
```

Then try again:

```
sudo apt update && sudo apt install -y libcs50
```

**Comment by mazenalimad** [comment]
@kzidane 

> $ curl -L https://packagecloud.io/cs50/repo/gpgkey | sudo apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
100  3933  100  3933    0     0   1258      0  0:00:03  0:00:03 --:--:-- 19279
gpg: can't connect to the agent: IPC connect call failed

> $ sudo apt update && sudo apt install -y libcs50
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Get:4 http://security.ubuntu.com/ubuntu focal-security InRelease [107 kB]
Get:5 https://packagecloud.io/cs50/repo/ubuntu focal InRelease [23.2 kB]
Err:5 https://packagecloud.io/cs50/repo/ubuntu focal InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 695BD8926FB7A037
Reading package lists... Done
W: GPG error: https://packagecloud.io/cs50/repo/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 695BD8926FB7A037
E: The repository 'https://packagecloud.io/cs50/repo/ubuntu focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by mazenalimad** [comment]
@kzidane 

> $ curl -s https://packagecloud.io/install/repositories/cs50/repo/script.deb.sh | sudo bash
[sudo] password for mrdalton:
Detected operating system as Ubuntu/focal.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/cs50_repo.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.

> $ sudo apt-get install libcs50
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libcs50

**Comment by kzidane** [comment]
That doesn't sound right. Sounds like there's a problem with your gpg-agent. Try restarting the gpg-agent daemon per this suggestion https://stackoverflow.com/a/47056403/1797347 or try restarting your machine and try the `curl` command again then try to install the library.

**Comment by mazenalimad** [comment]
Thank you very much for the help ^^ @kzidane 
I solved the problem by following the steps of this link : [https://docs.microsoft.com/en-us/windows/wsl/wsl2-install](url)

**Comment by Thecode764** [comment]
fix for mint?
