### ISSUE TITLE
Tu

### ISSUE THREAD

**Issue by Robert0RV** [cs50/libcs50#220]
U

**Comment by Ahmed0osman** [comment]
How can I solve this problem?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

‫في الاثنين، 31 أغسطس 2020 في 1:18 م تمت كتابة ما يلي بواسطة ‪David J.
Malan‬‏ <‪notifications@github.com‬‏>:‬
