### ISSUE TITLE
ubuntu 18.04 

### ISSUE THREAD

**Issue by jokerclay** [cs50/libcs50#221]
`cc     function.c   -o function
/tmp/cckEfPxd.o: In function `main':
function.c:(.text+0x1a): undefined reference to `get_string'
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'function' failed
make: *** [function] Error 1
`

**Comment by kzidane** [comment]
Assuming the library is installed correctly, be sure to link it with `-lcs50`.
