### ISSUE TITLE
MacOS Big Sur 11.1 - Apple Silicon M1 Macbook Air CS50 lib not working

### ISSUE THREAD

**Issue by Kasper-Liu** [cs50/libcs50#235]
Undefined symbols for architecture arm64:
  "_get_float", referenced from:
      _main in cash-a0c998.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [cash] Error 1

**Comment by Rubix982** [comment]
How are you compiling and running the code, exactly? This seems like a linking issue.

**Comment by Kasper-Liu** [comment]
My Code:
`mario.c`
`
#include <cs50.h>
#include <stdio.h>

int main(void)
{
int height;
    do
    {
      height = get_int("Height:");
    }
    while (height < 1 || height > 8);

    for (int line = 0; line < height;line++)
    {
        for (int spaces = height- line; spaces>1; spaces--)
        {
            printf(" ");
        }

        for (int hashes = 0; hashes < line +1;hashes++)
        {
            printf("#");
        }
        printf("\n");
    }
}
`

Terminal:
`make mario`

**Comment by Kasper-Liu** [comment]
@Rubix982 Thanks a lot! I solved it using `clang -lcs50 -o cash cash.c`

**Comment by Rubix982** [comment]
@Kasper-Liu I completely forgot about this issue. :facepalm: 
Happy coding!
