### ISSUE TITLE
get_string function prints out special characters instead of the given prompt

### ISSUE THREAD

**Issue by Nightmare247** [cs50/libcs50#240]
Here's my simple code- 

![image](https://user-images.githubusercontent.com/65822218/115331971-8c99b180-a1b4-11eb-84b1-971a974be80a.png)

I compile it with ``clang -lcs50 test2.c -o hello``
it generates no errors, but generates these warnings-

`test2.c:6:16: warning: implicit declaration of function 'get_string' is invalid in C99 [-Wimplicit-function-declaration]
    string s = get_string("Input: ");
               ^
test2.c:6:12: warning: incompatible integer to pointer conversion initializing 'string' (aka 'char *') with an expression of type 'int' [-Wint-conversion]
    string s = get_string("Input: ");
           ^   ~~~~~~~~~~~~~~~~~~~~~
2 warnings generated.
`

then when i execute it with `./hello`, i get this weird prompt
![image](https://user-images.githubusercontent.com/65822218/115331719-1006d300-a1b4-11eb-9972-aeeae4320d28.png)
this peice of code works fine on the online cs50 ide, so something must be wrong on my computer. Here's my computer's info-
![image](https://user-images.githubusercontent.com/65822218/115331790-39276380-a1b4-11eb-9801-458726de1755.png)
I'd installed the library with
`$ curl -s https://packagecloud.io/install/repositories/cs50/repo/script.deb.sh | sudo bash
$ sudo apt-get install libcs50
`
How do I fix this?

**Comment by nuoxoxo** [comment]
You have compiled the code with `-o`. As a result, `hello` will be an object. 

When you print an object out, it displays the machine language, hence the "special characters".

I think you can try again and compile it using `make` since you have the libcs50.

**Comment by dmalan** [comment]
@Nightmare247, sure you didn't take any other steps (e.g., manually editing `cs50.h` once installed)? I just did

```
$ docker run -it ubuntu:20.10
$ apt-get update
$ apt-get install -y clang curl sudo vim
$ curl -s https://packagecloud.io/install/repositories/cs50/repo/script.deb.sh | sudo bash
$ sudo apt-get install libcs50
$ vim test2.c # after which I added your code and saved
$ clang -lcs50 test2.c -o hello
```

and that indeed compiled and executed okay.

And what do you see if you execute `cat /usr/include/cs50.h`?

**Comment by Nightmare247** [comment]
@dmalan , nope I never edited the file, here's what I see when i do ``cat /usr/include/cs50.h``-
`/**
 * CS50 Library for C
 * https://github.com/cs50/libcs50
 *
 * Based on Eric Roberts' genlib.c and simpio.c.
 *
 * Copyright (c) 2020
 * All rights reserved
 *
 * BSD 3-Clause License
 * http://www.opensource.org/licenses/BSD-3-Clause
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 * * Redistributions of source code must retain the above copyright notice,
 *   this list of conditions and the following disclaimer.
 * * Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in the
 *   documentation and/or other materials provided with the distribution.
 * * Neither the name of CS50 nor the names of its contributors may be used
 *   to endorse or promote products derived from this software without
 *   specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
 * IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef CS50_H
#define CS50_H

#include <float.h>
#include <limits.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>

/**
 * Our own type for (pointers to) strings.
 */
typedef char *string;

/**
 * Prompts user for a line of text from standard input and returns the
 * equivalent char; if text is not a single char, user is prompted
 * to retry. If line can't be read, returns CHAR_MAX.
 */
char get_char(const char *format, ...) __attribute__((format(printf, 1, 2)));

/**
 * Prompts user for a line of text from standard input and returns the
 * equivalent double as precisely as possible; if text does not represent
 * a double or if value would cause underflow or overflow, user is
 * prompted to retry. If line can't be read, returns DBL_MAX.
 */
double get_double(const char *format, ...) __attribute__((format(printf, 1, 2)));

/**
 * Prompts user for a line of text from standard input and returns the
 * equivalent float as precisely as possible; if text does not represent
 * a float or if value would cause underflow or overflow, user is prompted
 * to retry. If line can't be read, returns FLT_MAX.
 */
float get_float(const char *format, ...) __attribute__((format(printf, 1, 2)));

/**
 * Prompts user for a line of text from standard input and returns the
 * equivalent int; if text does not represent an int in [-2^31, 2^31 - 1)
 * or would cause underflow or overflow, user is prompted to retry. If line
 * can't be read, returns INT_MAX.
 */
int get_int(const char *format, ...) __attribute__((format(printf, 1, 2)));

/**
 * Prompts user for a line of text from standard input and returns the
 * equivalent long; if text does not represent a long in
 * [-2^63, 2^63 - 1) or would cause underflow or overflow, user is
 * prompted to retry. If line can't be read, returns LONG_MAX.
 */
long get_long(const char *format, ...) __attribute__((format(printf, 1, 2)));

/**
 * Prompts user for a line of text from standard input and returns the
 * equivalent long long; if text does not represent a long long in
 * [-2^63, 2^63 - 1) or would cause underflow or overflow, user is
 * prompted to retry. If line can't be read, returns LLONG_MAX.
 */
long long get_long_long(const char *format, ...) __attribute__((format(printf, 1, 2)));

/**
 * Prompts user for a line of text from standard input and returns
 * it as a string (char *), sans trailing line ending. Supports
 * CR (\r), LF (\n), and CRLF (\r\n) as line endings. If user
 * inputs only a line ending, returns "", not NULL. Returns NULL
 * upon error or no input whatsoever (i.e., just EOF). Stores string
 * on heap, but library's destructor frees memory on program's exit.
 */
string get_string(va_list *args, const char *format, ...) __attribute__((format(printf, 2, 3)));
#define get_string(...) get_string(NULL, __VA_ARGS__)

#endif
`

**Comment by kzidane** [comment]
@Nightmare247 if you navigate to the folder where your source code file is and run the following commands, what is the output?

```
echo $0
cat ./test2.c
clang --version
clang ./test2.c -lcs50 -ohello
./hello
```

**Comment by jms41276** [comment]
Those warnings are what is seen when there's no <cs50.h> line. They can be promoted to errors with `clang -lcs50 -test2.c -o hello -Werror`. The problem recreates on my machine with that header not included, using the original compile command. Using gdb shows that `name` does get set to what it typed in. Or if aborted, that `get_string` from libcs50.so.10 was called. Could there be a path problem, some older cs50.h is found first?

**Comment by Nightmare247** [comment]
@kzidane here's the output of all the commands
![image](https://user-images.githubusercontent.com/65822218/115820163-ebae2f00-a41d-11eb-90c3-c466b06fe2aa.png)

**Comment by Nightmare247** [comment]
@jms41276 I thought at first that some older version was being used, so I reinstalled libcs50 with ``sudo apt remove libcs50 && sudo apt install libcs50``, but that didn't change anything, also, here;s the output of ``locate cs50.h`` if it helps in any way

![image](https://user-images.githubusercontent.com/65822218/115821443-6f691b00-a420-11eb-9bc1-39262c01637e.png)

**Comment by kzidane** [comment]
Sounds like you have multiple versions of `cs50.h`? If you installed the library using `apt` (or `apt-get`), you should only have `/usr/include/cs50.h`. Did you install the one at `/usr/local/include/cs50.h` manually? If so, can you try removing it or moving it somewhere else temporarily and try again?

**Comment by Nightmare247** [comment]
@kzidane Thank you so much! I moved ``/usr/include/cs50.h`` somewhere else and now it finally works!
