### ISSUE TITLE
fatal error: 'ctype.h' file not found

### ISSUE THREAD

**Issue by zienhub** [cs50/libcs50#249]
**When I was trying to install cs50 library, the terminal give these errors below:**
_(M1 mac with command-line-tools 13 installed, clang compile properly without cs50.)_
```
cc -Wall -Wextra -Werror -pedantic -std=c11 -fPIC -shared -Wl,-install_name,libcs50-10.1.1.dylib -o libcs50-10.1.1.dylib src/cs50.c
src/cs50.c:41:10: fatal error: 'ctype.h' file not found
#include <ctype.h>
         ^~~~~~~~~
1 error generated.
make: *** [Makefile:39: build/lib/libcs50-10.1.1.dylib] Error 1
```

**Comment by vicduraes** [comment]
Hello, Zien! 

I'm with the same problem here, in my linux mint system. Did you get install the lib?

**Comment by zienhub** [comment]
Hi Victoria,
    Sry for seeing this so late. As for your concerned, I finally gave up
building local workspace and switched to VS Code Code Space plugin which
works more fluent just like coding locally.
Hope that would help.
