### ISSUE TITLE
Getting error like : "Undefined symbols for architecture x86_64" while using get_int

### ISSUE THREAD

**Issue by doichev-kostia** [cs50/libcs50#250]
I am some kind of beginner in programming and absolute beginner in C and I don't know how to troubleshoot such error:

Undefined symbols for architecture x86_64:
  "_get_int", referenced from:
      _main in mario-89f3ee.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1

Used CLion IDE from JetBrains as CS50 IDE was loading extremely long.

I installed cs50 library as It was written on README. However, when I was trying to connect it using #include<cs50.h> and used get_int function, I got an error that I mentioned above.

```
#include <stdio.h>
#include <cs50.h>

void draw(int h);

int main(void) {

    int height = get_int("Height: ");
    draw(height);

    return 0;
}

void draw(int h) {
    for (int i = 1; i <= h; i++) {
        for (int j = 1; j <= i; j++) {
            printf("#");
        }
        printf("\n");
    }
}
```

[picture of error](https://drive.google.com/file/d/1SoetSHDzXIQn15mjMR7wls2bPlgohZFS/view?usp=sharing)

**Comment by dmalan** [comment]
On CS50 IDE, CS50 configures `make` with these defaults, using environment variables!

https://github.com/cs50/cli/blob/main/etc/profile.d/cli.sh#L57-L59

**Comment by doichev-kostia** [comment]
Thanks a lot
