### ISSUE TITLE
make's behaviour changed?

### ISSUE THREAD

**Issue by yashpalgoyal1304** [cs50/libcs50#255]
### Summary
Query regarding change in make's behaviour

### Details
* i attended "Week 1: C" from 2020's playlist/cs50 site. and on executing `make ----` it used to show which command it is running
* it was important as it helped me know that compiler is clang, and that the flags for error have to be explicitly used as well
* which immediately after helped me to expand and use that knowledge in getting libcs50 to work locally
* ref: 
    * [CS50 2020 - Lecture 1 - C @ 13:52]
    * screenshot: ![image](https://user-images.githubusercontent.com/19423063/145884189-80b0d8d0-c1cc-46bb-bc2f-4c4655bf9ebe.png)

+ but i just watched the 2021's video, and there it is hidden
+ ref: 
    + [CS50 2021 - Lecture 1 - C @ 28:31]
    + screenshot: 
![image](https://user-images.githubusercontent.com/19423063/145884653-557bf79c-2942-49c1-a562-b228803d29aa.png)

- is that intended? 
- if yes, what was the benefits of the change?
- can the commit link for the change be shared here?

-----
P.S.:
a dark-ish theme on vscode would have been better 😅 , this is like overly bright and comes directly at eyes while attending lecture

[CS50 2020 - Lecture 1 - C @ 13:52]: https://www.youtube.com/watch?v=zYierUhIFNQ&t=13m52s&list=PLhQjrBD2T382_R182iC2gNZI9HzWFMC_8&index=2
[CS50 2021 - Lecture 1 - C @ 28:31]: https://www.youtube.com/watch?v=LMUCmgghEXs&t=28m31s

**Comment by dmalan** [comment]
`make` is now aliased with a `-s` command-line argument, to simplify its output so that students only see errors:

https://github.com/cs50/cli/blob/main/opt/cs50/bin/make#L18

We decided that most of our `CFLAGS` are implementation details that weren't enlightening to show students (on every compilation) in the course's earliest weeks:

https://github.com/cs50/cli/blob/main/etc/profile.d/cli.sh#L49

As for the theme, the lighter theme was more visible on camera on stage!

**Comment by yashpalgoyal1304** [comment]
Thanks sir for the thorough input and sharing the location of make file.

I didnt know that make belonged to [CLI](https://github.com/cs50/cli) repo. sorry for opening this issue here 😅
i just saw a make file in root of this repo and thought it is same as that ('cz am not familiar with makefiles yet).


[transferring-an-issue-to-another-repository]

[CLI]: https://github.com/cs50/cli
[transferring-an-issue-to-another-repository]: https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository

**Comment by yashpalgoyal1304** [comment]
**update:**

use the make utility's option `--no-silent` to disable the `--silent` mode


```
$ make -vh                       # -v for version -h for help
GNU Make 4.3
... MORE ...
  -R, --no-builtin-variables  Disable the built-in variable settings.
  -s, --silent, --quiet       Don't echo recipes.
  --no-silent                 Echo recipes (disable --silent mode).
  -S, --no-keep-going, --stop
                              Turns off -k.
... MORE ...
```

![image](https://user-images.githubusercontent.com/19423063/186692589-c7679428-4a9f-43a9-939a-36bba3a7d924.png)
