### ISSUE TITLE
Compile C File throw error "ld: symbol(s) not found for architecture x86_64"

### ISSUE THREAD

**Issue by MeanAn1910** [cs50/libcs50#260]
Install the CS50 library following the instructions for macOS https://cs50.readthedocs.io/libraries/cs50/c/. Stuck on this error for years. I'm a newbie so I don't know how to solve this issue. Please support :<
```
ld: warning: ignoring file /usr/local/lib/libcs50.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
Undefined symbols for architecture x86_64:
  "_get_int", referenced from:
      _main in calculator0-bbacca.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
macOS hardware details:
<img width="461" alt="image" src="https://user-images.githubusercontent.com/83915952/159647865-9a407072-f4d0-4409-9d41-854b3e12dcb8.png">

**Comment by rongxin-liu** [comment]
Please email `sysadmins@cs50.harvard.edu` with the C file you are trying to compile. Thanks!
