### ISSUE TITLE
How can I solve this issue

### ISSUE THREAD

**Issue by Hajar537** [cs50/libcs50#269]
Hi everyone, can anyone help me to solve this issue because I'm still can't recognize the problem. 
And thanks in advance.
![VScode](https://user-images.githubusercontent.com/111440574/187718677-083ea230-e2ec-4d76-9f9b-7375bb5d886e.png)

**Comment by rongxin-liu** [comment]
From your screenshot, if you want to compile your calculation program, you would run:

`make calculation`

then

`./calculation`

**Comment by Hajar537** [comment]
> From your screenshot, if you want to compile your calculation program, you would run:
> 
> `make calculation`
> 
> then
> 
> `./calculation`

okay thank you so much
