### ISSUE TITLE
ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by msiahaan** [cs50/libcs50#273]
When I tried to make a program using  cs50 then, linker displays error:

> Undefined symbols for architecture x86_64:
>   "_get_char", referenced from:
>       _main in hello-3c8fc4.o
>   "_get_double", referenced from:
>       _main in hello-3c8fc4.o
>   "_get_float", referenced from:
>       _main in hello-3c8fc4.o
>   "_get_int", referenced from:
>       _main in hello-3c8fc4.o
>   "_get_long", referenced from:
>       _main in hello-3c8fc4.o
>   "_get_string", referenced from:
>       _main in hello-3c8fc4.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> gmake: *** [<builtin>: hello] Error 1

However if I manually using `clang -o hello -lcs50 hello.c`, it compiles successfully. Any ideas what went wrong with make? I am using iMac, MacOS Ventura, clang 12.0, GNU Make 4.4. Thank you

**Comment by rongxin-liu** [comment]
Your `make` command doesn't know what static library to include, and you likely need to create a proper Makefile if you want to use `make` command to compile your program.

You might want to consult this Makefile tutorial:
https://makefiletutorial.com/

In CS50 Codespace, we have set quite a few environment variables in the terminal and implemented our own `make` wrapper to simplify the compilation process:
https://github.com/cs50/cli/blob/main/etc/profile.d/cli.sh#L48-L51
https://github.com/cs50/cli/blob/main/opt/cs50/bin/make
