### ISSUE TITLE
Can't get MAX_INT and MAX_LONG with get_int, get_long and get_long_long functions like scanf.

### ISSUE THREAD

**Issue by Pointabc** [cs50/libcs50#275]
Can't get MAX_INT and MAX_LONG with get_int, get_long and get_long_long functions like scanf.

To fix this you need:
1 change in get_int fix
if (errno == 0 && *tail == '\0' && n >= INT_MIN && n < INT_MAX)
on
if (errno == 0 && *tail == '\0' && n >= INT_MIN && n <= INT_MAX)

2 and in get_long and get_long_long fix
if (errno == 0 && *tail == '\0' && n < LONG_MAX)
if (errno == 0 && *tail == '\0' && n < LLONG_MAX)
on
if (errno == 0 && *tail == '\0' &&)

In scanf these values can be obtained.

**Comment by Pointabc** [comment]
I wanted to create a branch but did not have enough rights.

**Comment by dmalan** [comment]
A good catch, but this is deliberate, so that `get_int` et al. can return a sentinel value in cases of error!
