### ISSUE TITLE
week 1 of CS50 2023

### ISSUE THREAD

**Issue by ibyteno8bit** [cs50/libcs50#279]
I am trying to complete the tests and I have issues when I copy the code provided in the lesson I get errors like these pasted below. I have opened multiple folders downloaded all types of extensions etc. The reason why I am not on the cloud version of vs code is because when I tried to open the terminal it said terminal not supported in the editor so I had to download and open vs code myself. As a beginner I have been working on setting up my work space for two days now and I am just going to ask for help because I feel like I did everything needed on my end, I followed every direction I could find online tried multiple ways, searched youtube and even uninstalled and installed things again in case I had missed something ... Any suggestions?
@ibyteno8bit ➜ /workspaces/libcs50 (main) $ code hello.c
@ibyteno8bit ➜ /workspaces/libcs50 (main) $ make hello
make: *** No rule to make target 'hello'.  Stop.
@ibyteno8bit ➜ /workspaces/libcs50 (main) $ ./hello
bash: ./hello: No such file or directory
@ibyteno8bit ➜ /workspaces/libcs50 (main) $

**Comment by rongxin-liu** [comment]
Please visit https://code.cs50.io and click "Login via GitHub" to access your codespace. If you have issues launching codespace, send a screenshot of the issue to sysadmins@cs50.harvard.edu.
