### ISSUE TITLE
I deleted the info in the main.yml folder by accident

### ISSUE THREAD

**Issue by GrantA-coder** [cs50/libcs50#282]
this is what it looks like now so I can't complete the practice problem. what should I do? 

<img width="960" alt="HW issue" src="https://user-images.githubusercontent.com/125323340/218605750-21662e32-e899-41ba-b923-ad487f0ccd23.PNG">

**Comment by dmalan** [comment]
Best to post such questions in https://cs50.harvard.edu/communities!

**Comment by GrantA-coder** [comment]
perfect, thank you!
