### ISSUE TITLE
How does the make command automatically link to the cs50 library or the libraries used?

### ISSUE THREAD

**Issue by mangefx** [cs50/libcs50#287]
I've been struggling with it all day and just found a way to create a makefile. But folders that do not contain makefile files will not automatically link to the cs50 library.

**Comment by dmalan** [comment]
See https://cs50.readthedocs.io/libraries/cs50/c/#makefile!

**Comment by goyalyashpal** [comment]
just saving for myself:
the `Makefile` itself can be made to essentially supply just the variables' definition to `make`, i.e. like the https://cs50.readthedocs.io/libraries/cs50/c/#environment-variables section, but without actually changing the environment variables

```makefile
# https://cs50.readthedocs.io/libraries/cs50/c/#makefile
# https://github.com/cs50/libcs50/issues/287

CC := clang

CFLAGS := -ferror-limit=1 -gdwarf-4 -ggdb3 -O0 -std=c11
CFLAGS += -Wall -Werror -Wextra
CFLAGS += -Wno-gnu-folding-constant -Wno-sign-compare
CFLAGS += -Wno-unused-parameter -Wno-unused-variable -Wno-unused-but-set-variable
CFLAGS += -Wshadow

# LDLIBS := -lcrypt -lcs50 -lm
LDLIBS := -lm

```

[win-symlink]: https://www.howtogeek.com/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/ "symlink on windows"

for using on windows, as these vars are essentially common to all the cs50x psets based on c-lang so, just `cmd /c mklink /h Makefile <pset>\Makefile` (ref: howtogeek/[win-symlink])
