### ISSUE TITLE
library doesn't work in windows

### ISSUE THREAD

**Issue by carlo8767** [cs50/libcs50#293]

**Comment by carlo8767** [comment]
From your instruction, it is not clear if your library is compatible with Windows.
I have tried but when I tried to use gets string testing =get_string("name") and import your library compare an error : 
In file included from helloCarlo.c:3:
cs50.c:78:28: note: expected 'char **' but argument is of type 'char *'
   78 | string get_string(va_list *args, const char *format, ...)
      |                   ~~~~~~~~~^~~~
helloCarlo.c:8:21: error: too few arguments to function 'get_string'
    8 |     string testing =get_string("name");

**Comment by carlo8767** [comment]
This is my file 👍 
#include<stdio.h>
#include"cs50.h"
#include"cs50.c"  
   
   
   int main(void){
            
    string testing =get_string("name");
    printf("Hello world\n");
    
   }

**Comment by rongxin-liu** [comment]
On Windows, please install WSL:
https://cs50.readthedocs.io/submit50/#installation
