### ISSUE TITLE
Plese provide clear instruction how to install your library in Windows

### ISSUE THREAD

**Issue by carlo8767** [cs50/libcs50#294]
From your instruction, it is not clear if your library is compatible with Windows.
I have tried several times to compile e run a simple code with your library in Vscode. 
Please provide a clear instructions or write inside the manual that it is not compatible with Windows.

**Comment by carlo8767** [comment]
I added the code : 
#include<stdio.h>
#include"cs50.h"
#include"cs50.c"  
   
   
   int main(void){
            
    string testing = get_string("?");
    printf("Hello world\n");
    
   }

**Comment by rongxin-liu** [comment]
`libcs50` is not compatible with Windows natively. To use it:

1. Please install Windows Subsystem for Linux
2. Choose Ubuntu distro 
3. Install libcs50 inside WSL.

Or use https://cs50.dev online, or use Codespaces offline:
https://cs50.readthedocs.io/code/#offline-with-docker
