### ISSUE TITLE
A suggestion for CS50 Manual Pages

### ISSUE THREAD

**Issue by novusnota** [cs50/libcs50#305]
I hope this is the right place for suggesting things related to https://manual.cs50.io

![image_2023-09-02_17-42-11](https://github.com/cs50/libcs50/assets/68142933/90106e46-a62a-4818-9511-6a0449b58be9)

On that page there is a switch called "less comfortable" for showing only libraries/headers with user-friendly descriptions available. Similar switches are also present on the library/header pages.

My suggestion to rename those switches from _"less comfortable"_ to _"I am less comfortable"_ as it's currently ambiguous whether they refer to the person being less comfortable with the C language, **or** to the library/header being less comfortable to use.

**Comment by dmalan** [comment]
Thank you, we indeed ended up tweaking!

https://manual.cs50.io/
