### ISSUE TITLE
Code recognises the cs50.h library but throws error when 'make' is used and compiles with 'gcc'.

### ISSUE THREAD

**Issue by thesairam** [cs50/libcs50#332]
I am using Ubtunu  and VSCODE. 

I installed the library as per instructions and my code sees the cs50.h library and recognizes the functions too!

However, when I use make hello, it throws me this error:
sairam@Sairam:~/learning/cs50/Week1$ make hello
cc     hello.c   -o hello
/usr/bin/ld: /tmp/ccEEuwsb.o: in function `main':
hello.c:(.text+0x44): undefined reference to `get_string'
collect2: error: ld returned 1 exit status
make: *** [<builtin>: hello] Error 1

When I use sairam@Sairam:~/learning/cs50/Week1$ gcc -o hello hello.c -lcs50
It works fine. 

Super weird error. Can anyone help me to fix please to work with make. 

![image](https://github.com/user-attachments/assets/ab77cb63-7176-48ef-be71-47385b756649)

**Comment by thesairam** [comment]
My bashrc has the following:
export LIBRARY_PATH=/usr/local/lib
export C_INCLUDE_PATH=/usr/local/include
export LD_LIBRARY_PATH=/usr/local/lib


and I modified the config JSON in Vscode too and created tasks.json, nothign worked

![image](https://github.com/user-attachments/assets/aa5c2a28-5a97-4662-8634-288ffee3644e)

**Comment by thesairam** [comment]
***@***.***:~/learning/cs50/Week1$ make hello -lcs50
clang -ferror-limit=1 -gdwarf-4 -ggdb3 -O0 -std=c11 -Wall -Werror -Wextra -Wno-gnu-folding-constant -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-but-set-variable -Wshadow    hello.c  -lcrypt -lcs50 -lm -o hello
make: clang: No such file or directory
make: *** [<builtin>: hello] Error 127
***@***.***:~/learning/cs50/Week1$

I am still getting this error, clearly I tried them all and its not a fix.

Could you please help me set up it correctly?

Thanks
________________________________

**Comment by dmalan** [comment]
Sounds like you don't have `clang` installed. (`sudo apt install clang`) But best to use https://cs50.dev for CS50!

**Comment by thesairam** [comment]
Sure, let me try it out.
Haha installing this in my own VScode that runs on Ubuntu seems like really a great learning for me .

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by thesairam** [comment]
[cid:2322f3cd-b9df-4ba3-92b4-c070596af232]
Finally worked! 🙂
Thank you

________________________________
