### ISSUE TITLE
change get_* to accept a prompt as argument

### ISSUE THREAD

**Issue by dmalan** [cs50/libcs50#50]
Instead of re-prompting user in cases of invalid input with `Retry:`, should instead just re-prompt user with argument. I.e.:

``` c
string get_string(string prompt);
```

Planned for Fall 2017.

**Comment by kzidane** [comment]
Or maybe `get_string(string prompt, string retryPrompt)` in case they're different?

**Comment by dmalan** [comment]
Mm, adds unnecessary complexity I'd say!

**Comment by kzidane** [comment]
Was just thinking about the scenario where hint may be provided to the user, in case she doesn't co-operate. But yeah, probably unnecessarily complex.

**Comment by IvanJasenov** [comment]
@dmalan What about making the input more interactive. Parse the raw input at first, check for what eventually went wrong i.e. float instead of int and for each bad input suggest a change which will be hard coded in the library?

**Comment by IvanJasenov** [comment]
@dmalan To which function this feature should be applied to? Just `get_string` or all?
I think it will be good to set number of tries, and if user still makes a mistake, provide him with the appropriate man page for the function.

**Comment by dmalan** [comment]
Oops, sorry for missing this, the vision for this new variant is that it'd behave identically to the current version except that the user would see the prompt 1 or more times ( and instead of `Retry:`). Though we're not sure yet how we could roll this out seamlessly with CS50 AP still in progress, so no need to forge ahead yet!

**Comment by dmalan** [comment]
@crossroads1112, @glennholloway, @kzidane:

Inspired by https://gustedt.wordpress.com/2010/06/03/default-arguments-for-c99/, I started working on this, porting the idea to a 0-or-1 argument scenario, https://github.com/cs50/libcs50/blob/optional-args/src/cs50.h#L49-L60.

A function like `get_int` is then declared as https://github.com/cs50/libcs50/blob/optional-args/src/cs50.h#L123-L125.

This works as intended when compiled with `std=c89` and `std=gnu99` but not when `std=c99` is used, which appears to trigger `__STRICT_ANSI__`, per http://stackoverflow.com/a/5331540. The result is that compiling the library yields:

```
$ make build
rm -rf "build"
mkdir -p "build/usr/include" "build/usr/lib" "build/usr/share/man/man3" "build/usr/src"
gcc -c -fPIC -std=c99 -Wall -o "build/cs50.o" "src/cs50.c"
src/cs50.c:224:12: error: too few arguments to function call, single argument 'prompt' was not specified
    return get_int();
           ^~~~~~~~~
src/cs50.h:61:22: note: expanded from macro 'get_int'
#define get_int(...) ZERO_OR_ONE_ARG(get_int, ##__VA_ARGS__)
                     ^               ~~~~~~~
src/cs50.h:60:97: note: expanded from macro 'ZERO_OR_ONE_ARG'
#define ZERO_OR_ONE_ARG(NAME, ...) NAME(_ZERO_OR_ONE_ARG(NAME, ARGS(__VA_ARGS__), ##__VA_ARGS__))
                                   ~~~~                                                         ^
src/cs50.c:196:1: note: 'get_int' declared here
int get_int(string prompt)
^
1 error generated.
make: *** [build] Error 1
```

even though the macros ensure that, after preprocessing, `get_int` is indeed called with exactly one argument. Unfortunately, that output doesn't provide a hint (with the usual square brackets) as to how we might suppress that error with a flag.

Thoughts on how best to resolve?

Note that these new `get_*` functions (e.g., https://github.com/cs50/libcs50/blob/optional-args/src/cs50.c#L199-L234) aren't yet fully implemented. The goal for the coming year is:

* if `get_*` is called with an explicit prompt, display (and re-display) that prompt as needed
* if `get_*` is called without an explicit prompt, display no prompt (as in Fall 2016) but re-display `Retry: ` (an implicit prompt) as needed
* if `Get*` is called without an explicit prompt, behave as in Fall 2014, but display deprecation warning at compilation time
* if `Get*` is called with an explicit prompt, don't compile

**Comment by dmalan** [comment]
PS, the goal is only to support these several modes for a year. After Fall 2018, we'd remove `Get*` altogether and also require an explicit prompt for `get_*`.

**Comment by dmalan** [comment]
Actually, this seems to be the result of disparate behavior when you're explicitly in `std=c99` mode, per https://gcc.gnu.org/onlinedocs/cpp/Variadic-Macros.html:

> ... the ‘##’ token paste operator has a special meaning when placed between a comma and a variable argument. If you write
>
> `#define eprintf(format, …) fprintf (stderr, format, ##__VA_ARGS__)`
>
> and the variable argument is left out when the eprintf macro is used, then the comma before the ‘##’ will be deleted. This does not happen if you pass an empty argument, nor does it happen if the token preceding ‘##’ is anything other than a comma.
> ...
> CPP retains the comma when conforming to a specific C standard. Otherwise the comma is dropped as an extension to the standard.

In particular, if you compile

```
#define get_int(...) ZERO_OR_ONE_ARG(get_int, ##__VA_ARGS__)
...
int i = get_int();
```

as `foo.c` with `gcc -E foo.c`, you get

```
int i = ZERO_OR_ONE_ARG(get_int);
```

as intended. But if you compile the same with `gcc -E -std=c99 foo.c`, you get

```
int i = ZERO_OR_ONE_ARG(get_int,);
```

with the undesired extra comma.

Thoughts on thus changing the `Makefile` not to specify `std` explicitly? What might break on wha platforms?

**Comment by dmalan** [comment]
Discussed in person.
