### ISSUE TITLE
Error messages when __attribute__ unsupported are non-obvious

### ISSUE THREAD

**Issue by crossroads1112** [cs50/libcs50#59]
A post was made on /r/cs50 recently about someone attempting to use the library on Windows but the build failing due to a syntax error on the use of `__attribute__` as these are not supported by MSVC. It would be fairly trivial to add a check for this in `cs50.h`, the only question being whether this should result in a warning (since no features essential to the functionality of the library rely on `__attribute__`) or simply an error with our own user-friendly error message. The two solutions could look something like the following:

Warning:

    #ifndef _GNUC
        // Can't use #warning because it is not available on MSVC
        #pragma message "Message explaining that the library relies on certain extensions and that certain things will not work (IO buffering, memory cleanup etc.)
        // Silence syntax errors
        #define __attribute__(X)
    #endif

Error:

    #ifndef _GNUC
        #error "Message like the above, perhaps suggesting that students who use Windows try MinGW"
    #endif

**Comment by crossroads1112** [comment]
A third alternative, if we wanted to make pains to make this work on Windows, would be to do something like what is suggested in [this](http://stackoverflow.com/questions/1113409/attribute-constructor-equivalent-in-vc) StackOverflow question, but that may just clutter up the library unnecessarily.

**Comment by dmalan** [comment]
Hm, if we do support MSVC, it should probably be with garbage collection, particularly as we roll out Mac/Linux/Windows support for `help50`, `check50`, et al. I wonder if http://stackoverflow.com/questions/1113409/attribute-constructor-equivalent-in-vc#comment53865158_2390626 is still an issue. 

@kzidane would you want to take a stab at this?

CC @glennholloway, @rbowden91

**Comment by Sebbyastian** [comment]
A resolution to this issue can be provided in _portable_ C code. Why resort to using non-portable extensions?

More importantly, I'm fairly sure `setup` and `teardown` don't actually _solve_ the problem of memory leaks, but instead _mask_ it (see #68). Wouldn't it be better to teach your students how to use `valgrind` as part of week 2 to identify and eliminate memory leaks and various other memory-related problems?

**Comment by dmalan** [comment]
See https://github.com/cs50/libcs50/issues/67#issuecomment-301538122!

**Comment by crossroads1112** [comment]
Resolved by ecbc40b
