### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by ankitrgadiya** [cs50/libcs50#61]
I'm on Archlinux, I downloaded the latest release zip and tried installing it on my system. 
```
[elliot@Tesla](libcs50-7.1.1) $ make install
rm -rf "build"
mkdir -p "build/usr/include" "build/usr/lib" "build/usr/share/man/man3" "build/usr/src"
gcc -c -fPIC -std=c99 -Wall -Werror -o "build/cs50.o" "src/cs50.c"
gcc -o "build/usr/lib/libcs50.so" -shared "build/cs50.o"
rm -f "build/cs50.o"
cp "src/cs50.h" "build/usr/include"
cp "src/cs50.c" "build/usr/src"
cp -r docs/* "build/usr/share/man/man3"
find "build" -type d -exec chmod 0755 {} +
find "build" -type f -exec chmod 0644 {} +
cp "build/usr/include/*" /usr/include
cp: cannot stat 'build/usr/include/*': No such file or directory
make: *** [Makefile:80: install] Error 1
```

So, it failed. 
Then I tried compiling and installing manually and it worked. I suspect something is wrong in Makefile.

**Comment by crossroads1112** [comment]
Are you talking about the latest release zip on the AUR, or on GitHub?

**Comment by kzidane** [comment]
@ankitrgadiya oops! This's been fixed actually, but I forgot to create a new release. Please try again with the release I just created https://github.com/cs50/libcs50/releases/tag/7.1.2! Sorry for the inconvenience!

**Comment by ankitrgadiya** [comment]
@crossroads1112 I was talking about Github release. @kzidane Thanks I'll try it.
