### ISSUE TITLE
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by Abyss0043040** [cs50/libcs50#62]
I install the cs50 in ubuntu using your instruction but when I compile some test file using clang I get this error.

machine@DESKTOP-7K00UM0:~/libcs50-7.1.2/tests$ clang eprintf.c
/tmp/eprintf-ecd946.o: In function `main':
eprintf.c:(.text+0x24): undefined reference to `eprintf'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by crossroads1112** [comment]
You need to tell clang to link the CS50 library. Try compiling with `clang eprintf.c -lcs50`

**Comment by kzidane** [comment]
As @crossroads1112 said. Watch [Compilers](https://youtu.be/CSZLNYF4Klo) and [Libraries](https://youtu.be/ED7QtgXDShY) for more information!

**Comment by Abyss0043040** [comment]
Hi Guys

I see.. Thank you for this :)
