### ISSUE TITLE
tidy Makefile

### ISSUE THREAD

**Issue by dmalan** [cs50/libcs50#63]
Has gotten a bit unwieldy with so many variables. Harder to follow build process for students.

**Comment by dmalan** [comment]
@kzidane are you using `Makefile` still or can we simplify it just to support `make`, `make install`, and `make hackerrank` for folks to use on their own machines?

**Comment by kzidane** [comment]
Yes, still using https://github.com/cs50/libcs50/blob/launchpad/Makefile. Should we add `make hackerrank` too?

**Comment by dmalan** [comment]
Yup, let's add that one back, and let's also install to `$DESTDIR`, whose default value can be `/usr` so that folks can override by running `DESTDIR=/some/path make install`?

**Comment by kzidane** [comment]
Added per b95b2aa!
