### ISSUE TITLE
Optimistic bounds check causes potential memory leaks and off-by-one or null pointer dereference

### ISSUE THREAD

**Issue by Sebbyastian** [cs50/libcs50#66]
```
    // cs50.c#L280
    if (allocations == SIZE_MAX)
    {
        return NULL;
    }
    // ...
    // cs50.c#L365
    string *tmp = realloc(strings, sizeof(string) * (allocations + 1));
    // ...
    //cs50.c#L374
    strings[allocations] = s;
```

Optimistically, this code would be able to allocate `SIZE_MAX` elements of `char *` (L280).

Realistically, `sizeof (string)` is commonly greater than 1 and thus the multiplication at L365 is likely to cause unsigned integer wrapping long before then; at this point L365 will equate to `string *tmp = realloc(strings, 0);`. Either a/ an array suitable to allocate 0 `char *` elements will be created, or b/ `strings` will be `free`d and `realloc` will return a null pointer.

At L374 you have an assignment into a/ an array that can't contain any elements, or b/ a null pointer.

**Comment by crossroads1112** [comment]
Good catch! I can't think of an architecture which would have `sizeof (char*)` be 1 (it'd almost have to be 8-bit). 

Should be a simple fix in any case:

    if (allocations == SIZE_MAX /sizeof (string))

**Comment by Sebbyastian** [comment]
Yes. The fix is simple.

> I can't think of an architecture which would have sizeof (char*) be 1 (it'd almost have to be 8-bit).

`char *` can't be represented using 8 bits, as the C standard requires that objects up to 65536 bytes in size be supported (see [section 5.2.4](http://port70.net/~nsz/c/c11/n1570.html#5.2.4)).

An architecture which evaluates `sizeof (char *) == 1` truthfully would also need to evaluate `CHAR_BIT >= 16` truthfully. This could be true for various DSP architectures, which might also evaluate `sizeof (int) == 1` truthfully, for example. It's a shame the tutorial doesn't teach any of this **portable** language we call C, instead defaulting to teaching only about extended _common_ implementations; I wouldn't call this a C tutorial so much as a "C using an x86 LLP64/IL32P64 or LP64/I32LP64 integer representation" (see [this page which explains 64-bit data models](https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models)); such a tutorial isn't really teaching C, but a slightly different, extended language which has subtle and possibly devastating differences when trying to port code to more basic systems.

You should consider learning/teaching in terms of [ranges guaranteed by the standard](http://port70.net/~nsz/c/c11/n1570.html#5.2.4), which doesn't necessarily correlate to _size of data types_. For example, [the section dealing with "sizes of integer types"](http://port70.net/~nsz/c/c11/n1570.html#5.2.4.2.1) doesn't actually specify the sizes, as it assumes there may be padding bits which aren't generally useful to know about [see section 6.2.6.2](http://port70.net/~nsz/c/c11/n1570.html#6.2.6.2).

**Comment by crossroads1112** [comment]
Very interesting! Thanks!

>  It's a shame the tutorial doesn't teach any of this portable language we call C

I disagree with this pretty strongly. That's pretty far outside the scope of the course IMO. In my opinion, the course isn't really about teaching C per se. Rather, C is a tool used to introduce various concepts in CS. Discussions of the portability of C almost invariably (as it did in this thread) turn into discussions of computer architecture which, in my opinion, is well outside the scope of the course. In a general CS course, I would have no problem saying "the size of an `int` is dependent on the architecture of the machine, but it's 4 bytes in the scope of this course". If students are really interested in computer architecture, they can take a computer architecture class or an embedded systems class.
