### ISSUE TITLE
Complex, pervasive memory leaks throughout user input functions

### ISSUE THREAD

**Issue by Sebbyastian** [cs50/libcs50#67]
Various library functions (`get_char`, `get_double`, `get_float`, `get_int`, `get_long_long`) make use of the function `get_string` which allocates memory; the functions then perform a transformation of that memory and return, without `free`ing the memory that was allocated, which is extremely unlikely to be used again, aside from being `free`d at the end of the program. The result may not appear via `valgrind` etc, but may have performance implications nonetheless, particularly when used in an infinite loop where the end of the program is unforeseeable. `get_string` also has this problem; there's no way for the caller to tell the library that they're finished with a string, so they (intentionally) leak its reference and it just... stays there... until the program exits.

Unfortunately this could impact the performance of certain testing methods (e.g. fuzzing) so drastically that programs written using these functions are likely to be untestable using those methods.

This issue is likely to be reproduced by a program that merely reads characters using `get_char` one after the other, and discards the reference to them in a typical manner... and piping input from `/dev/random`.

One fix might involve providing a function that deallocates and removes the reference of a string from the table. The C standard, for example, contains an equivalent function, called `free`.

**Comment by dmalan** [comment]
This is by design, actually. We use the CS50 Library in the first few weeks of class so as to abstract away the underlying implementation of strings in C. Having students call `free` (or, e.g., `free_string`) in the course's earliest weeks would break that abstraction barrier and require introducing memory management sooner than we feel is ideal. We only recently introduced `setup` and `teardown` via extensions so as to garbage-collect memory before a process's termination so that any errors reported by `valgrind` mid-semester (while we're still using the library but introducing memory management) related to students' code, not library code.

**Comment by crossroads1112** [comment]
@dmalan IMO, It might not be a bad idea to still free the strings allocated by `get_*` internally, unless this would clutter up the library unnecessarily. This doesn't have to change the student-facing API and fixes a regression that introducing garbage collection introduced. Not a huge deal since the amount of memory will probably be small, but it wouldn't be too hard to fix.

**Comment by dmalan** [comment]
Not opposed, but it does feel like an over-optimization. The reality is, in a typical CS50 program, these functions are called very few times.

**Comment by Sebbyastian** [comment]
> ... it does feel like an over-optimization ...

What, to mask memory leaks? Agreed, as the OS would clean up that code anyway...

> ... the underlying implementation of strings in C.

On the topic of strings and masking errors, introducing the concept of "strings" as a type masks the error of the teacher explaining the truth of the concept: a pattern of values. You could teach floating point constants as a sequence of digits where the integer portion ends at the first period, and then teach strings as a sequence of characters that ends at the first `'\0'` to establish the pattern... This would be reasonably compatible with the C standard, but it's easier lie to your students because they won't understand this _apparently complex_ pattern, right?

It might also seem easier to correct the complex misunderstanding that arises from teaching incorrectly than to teach correctly the first time, but your students likely move on before that has to happen, leaving the mess to someone else to clean up. What a fine example that would be to set! Leave messes for other people to clean up. That reminds me of... everything that's wrong with the I.T. industry!

> ... so as to garbage-collect memory before a process's termination so that any errors reported by valgrind mid-semester (while we're still using the library but introducing memory management) related to students' code ...

You seem to believe this is garbage collection, yet by the references I've read (which _are_ intended for beginner computer programmers, by professors and have stood the test of time as some of the most reputable computer science books for over twenty years) that's a **very generous** term to use to describe such a basic algorithm. Your "garbage collection" converts a simple leak into an [extremely complex leak, the kind which leak-resistant technologies such as `valgrind` and Rust can't identify](https://doc.rust-lang.org/nomicon/leaking.html):

> It's quite trivial to initialize a collection at the start of a program, fill it with tons of objects with destructors, and then enter an infinite event loop that never refers to it. The collection will sit around uselessly, holding on to its precious resources until the program terminates (at which point all those resources would have been reclaimed by the OS anyway).

Similarly, `system("pause")` (which shares the non-portability of this _garbage collection_) masks the error of "making the console program pause at the end". The proper solution to that problem is to teach the student about the console, so that they can see how to write code for the console _or_ teach the student about the GUI, so that they can see how to write code for the GUI)... _It must be easier to teach C than to teach how to use the console, right?_

**The fact that there's memory which is neither useful nor freed constitutes a memory leak in any language.** That's the bottom line. Sorry, but your _garbage collection_ fails to collect garbage appropriately. Perhaps you should use a JVM-targeting compiler, so you don't have to implement this hack?

**The most appropriate solution** might be to teach the students to write code that doesn't violate [Dependency Inversion Principle](https://en.wikipedia.org/wiki/Dependency_inversion_principle)_. Indeed, you don't need to cover _memory management_ at an early stage to teach C (cleanly); you might notice `fgets`, `fscanf`, `strto*`, in fact _most C standard functions_ don't force you to use _allocated storage_ by returning something that has _allocated storage duration_. You can decide to use _automatic storage duration_ when it's most suitable. The majority of the C standard library, in fact, is designed this way for a reason: to reduce the kind of code rot that violations of the DIP cause. **What kind of example do you want to set?**

If I haven't managed to convince you that this is a _bad idea_, and you want to implement this in a _less non-portable_ manner, add a function prototype for `int enter();`, then implement `main` within the library to call your `setup` function and [register your `teardown` function using `atexit`](http://www.iso-9899.info/n1570.html#7.22.4.2) before you `return enter(argc, argv);`.  You could then hide this abstraction by inserting `#define main entrance` into `<cs50.h>`. i.e.

`/* BEGIN cs50.c */
#include <stdlib.h>
#include <stdio.h>

void setup(void) {
	puts("setup called");
}

void teardown(void) {
	puts("teardown called");
}

int enter();
int main(int argc, char **argv) {
	setup();
	atexit(&teardown);
	return enter(argc, argv);
}
/* END cs50.c */

/* BEGIN <cs50.h> */
#define main enter
/* END <cs50.h>

/* USER PROGRAM */
int main(void) {
	exit(0);
}`

**Comment by crossroads1112** [comment]
Disclaimer: I in no way speak for CS50, just myself.

> It might also seem easier to correct the complex misunderstanding that arises from teaching incorrectly than to teach correctly the first time, but your students likely move on before that has to happen, leaving the mess to someone else to clean up. 

This is how education works. Every introductory mechanics course introduces momentum as `p = mv`, not `p = mv/sqrt(1-v^2/c^2)` because the latter requires an understanding of general relativity which itself requires an understanding of mechanics and also because its a really good heuristic for particles not traveling near the speed of light.

Initially hiding the complexity of strings is the same principle, except it's actually better because the complexity is only hidden for a couple of lectures before it is revealed, unlike relativity which is almost never taught in introductory courses. 

> You could teach floating point constants as a sequence of digits where the integer portion ends at the first period, and then teach strings as a sequence of characters that ends at the first '\0' to establish the pattern... 

Aside from the fact that that's not how floats are represented (introducing one of those pesky misconceptions), that is how strings are taught in the course. Furthermore, floats are fixed-width meaning they can be stack allocated and are thus conceptually much simpler. Teaching strings (string-literals aside) requires introducing the heap (and thus, the stack) as well as pointers (and furthermore how they differ from arrays) which are a notorious pain point for newcommers in C. These are eventually explained in the course, but throwing complexity at people before they develop an interest in the subject is why CS has a reputation of inaccessibility.

It raises the question though, why stop there? Why allow students to assume an ASCII representation? UTF-8 (and to a lesser extent UTF-16) are how text is represented in the real world and they are notoriously complicated. It's much easier to teach the basics if you can pretend that there are only 128 fixed-width characters instead of having to define what you even mean by "character" (codepoint? grapheme?).

> The proper solution to that problem is to teach the student about the console, so that they can see how to write code for the console or teach the student about the GUI, so that they can see how to write code for the GUI).

This is an introductory course, which, in my opinion, does a really great job of introducing a lot of CS concepts (binary trees, tries, hash tables, ASCII, dynamic memory, etc.). That's outside the scope of the course.

> Sorry, but your garbage collection fails to collect garbage appropriately. 

That's not what it's trying to do though. You're right, garbage collection is perhaps poor-wording; it's error suppression, but that's all it needs to be. This library isn't meant to be used in 'real' programs; it's meant to create some abstractions that students use when they are getting started with the course material. Abstractions, by the way, that are eventually revealed.

> fgets, fscanf, strto*

These all have novice-unfriendly potential gotchas. `fgets` requires you to know a maximum buffer size beforehand, which you don't always know (though this doesn't cause undefined behavior). `fscanf` has all kinds of possible undefined behaviors, even when used correctly. `strto*` requires the introduction of `errno` (talk about setting a poor example) and pointers to be used properly.

> You could then hide this abstraction by inserting #define main entrance into <cs50.h>...

This mangles debugging symbols.  GDB's `break main` won't do what students expect.

**Comment by Sebbyastian** [comment]
> Initially hiding the complexity of strings is the same principle, except it's actually less severe because the complexity is only hidden for a couple of lectures before it is revealed.

_What complexity?_ Explaining strings as I explained them (correctly) is _simpler_ than correcting the misunderstanding CS50 seems to be teaching. Allow me to demonstrate.

> ... that's not how floats are represented...

Indeed, but it is how floating point _constants_ are represented. See [C11/6.4.4.2p2](http://www.iso-9899.info/n1570.html#6.4.4.2p2) for a citation, if you must...

> ... that is how strings are taught in the course ...

A.K.A. incorrectly, and in a way that probably leaves the mess for someone else to clean up later. For example, you _still_ seem confused, likely despite making your entire way through the course... Well, hopefully I can clear that up for you.

> Furthermore, floats are fixed-width meaning they can be stack allocated ...

As can strings be. It's important to understand how _string literals are constants_ that are _usually_ (but not always; see [C11/footnote 78](http://www.iso-9899.info/n1570.html#FOOTNOTE.78)) converted to _string values_, and equally important to understand how _floating point constants_ are converted to _floating point values_. Do you see the pattern? Perhaps not. Allow me to make it more explicit:

_X constants_ are _usually_ converted to _Y values_.

For X, insert "string literal" or "floating point". For Y, insert "string" or "floating point", respectively.

Is that _really_ difficult to understand? I maintain my position that the lessons currently introduce _more_ complexity than that, later on.

    int fubar(void) {
        static int x;
        float y;
    }

What storage duration does `x` have? What about `y`? And their storage durations? Is it guaranteed that `x` will lie in the _stack_? Or might it be assigned to a _register_, instead? Do you now see how teaching `float` and `int` objects as though they're attached to a specific storage duration ("stack allocated", as you claim, when I think you meant "automatic storage duration") is an error?

> ... stack allocated ...

Quoting from the standard, "There are four storage durations: static, thread, automatic, and allocated". Five if you count the temporary extension of automatic storage duration when a function returns a `struct` type of data. See [C11/6.4.2](http://www.iso-9899.info/n1570.html#6.4.2) for more information. I'm fairly sure you mean "objects with automatic storage duration".

Nonetheless, teaching _strings_ as though they have _allocation type_ in any form is an error, just as teaching _floats_ and _ints_ as though they have _allocation type_.

> Teaching strings (string-literals aside) requires introducing the heap (and thus, the stack) as well as pointers (and furthermore how they differ from arrays) which are a notorious pain point for newcommers in C.

No, it doesn't. A string is a particular pattern of "array value" (that is, if you consider the entirety of the array when you inspect its value); the pattern is: a sequence of characters that terminates at the first `'\0'` byte. See [C11/7.1p1](http://www.iso-9899.info/n1570.html#7.1p1) as a citation. Similarly, a floating point _constant_ is: a sequence of decimal digits which has an integer portion that terminates at the first period. Again, see [C11/6.4.4.2p2](http://www.iso-9899.info/n1570.html#6.4.4.2p2) for a citation.

I hope I've helped you to avoid making that kind of categorical error again.

> Why allow students to assume an ASCII representation?

Indeed. Why teach students to assume that `'a'` has the integer value 97, and so they can use 97 instead?  That's 1/ not guaranteed by the standard and 2/ teaching students to use magic numbers (and then later back-peddling by teaching them that it's bad to use magic numbers). Why teach students that `'a'` and `'A'` have a difference of 32, when you could just skip that and jump to the more portable, and less hideous assumption: that you can test and convert character values using `isalpha`, `islower`, `isupper`, `tolower`, `toupper` and so forth?

> UTF-8 (and to a lesser extent UTF-16) is how text is represented in the real world and they are notoriously complicated.

It's a good thing that's not required to teach C, then, huh? See [C11/6.10.8.2](http://www.iso-9899.info/n1570.html#6.10.8.2), [C11/Annex J.3](http://www.iso-9899.info/n1570.html#J.3) and various other references.

> It's much easier to teach the basics if you can pretend that there are only 128 fixed-width characters instead of having to define what you even mean by "character" (codepoint? grapheme?).

If your intention is to simplify things, the only characters guaranteed _portably_ are listed within [C11/5.2](http://www.iso-9899.info/n1570.html#5.2). There are _less_ than 128 of them, and as such this character set is _even simpler_ than ASCII. All you have to do is lose the "ASCII reliance" errors, and the entire course will most likely still make perfect sense.

C has a rather specific definition for the term "character". It is: "bit representation that fits in a byte". See [C11/3.7.1](http://www.iso-9899.info/n1570.html#3.7.1)... While you're there, note the definitions for "multibyte character" and "wide character", which rely upon some locale-specific (and thus implementation-defined) behaviour.

Also noteworthy: A byte is: "addressable unit of data storage large enough to hold any member of the basic character set of the execution environment". That's from [C11/3.6](http://www.iso-9899.info/n1570.html#3.6).

> This is an introductory course, which, in my opinion, does a really great job of introducing a lot of CS concepts (binary trees, tries, hash tables, ASCII, dynamic memory, etc.).

It certainly teaches about the console, `gdb` and `make`. Regretfully, **it doesn't also teach immensefully useful, up-to-date technology such as valgrind**, which isn't a far stretch and _might just be useful for catching other kinds of common mistakes_.

> ... it's error suppression ...

For what purpose? Hiding the errors from people who know how to use valgrind (which is something the course doesn't teach)? That seems like a solution to a non-problem, doesn't it? Why not just remove this error suppression altogether, and leave it for the _common_ OS to handle; as it is the course assumes ASCII so with that in mind, it'd be safe to assume the OS will clean this mess up, too! Which side of the fence do you want to sit?

> These all have novice-unfriendly potential gotchas. `fgets` requires you to know a maximum buffer size beforehand, which you don't always know (though this doesn't cause undefined behavior).

No, it doesn't. It leaves the remainder of the line unread, when the buffer is full. This can be detected by using testing `buffer[strcspn(buffer, "\n")]`, which also seems relatively simple. The options from there are simple to understand, too. Either 1/ discard the remainder (e.g. `fscanf(stdin, "%*[^\n]); fgetc(stdin);`, perhaps informing the user that truncation was performed, which I commonly recommend wrapping into a function named something like `discard_line` to people who erroneously use ~~`fflush(stdin)`~~, perhaps includable in `<cs50.h>`... note that this is **killing two birds with one stone**) or 2/ `realloc` to double the size of the buffer and call `fgets` again (more advanced, could be taught later on)...

In the case of the first option, the maximum buffer size is most certainly not necessary.

Furthermore, assuming that a CS student can't learn what `strcspn` does by a simple explanation seems like an insult to me.

> This mangles debugging symbols. GDB's `break main` won't do what students expect.

As it is, valgrind won't do what some students expect. :(

Here's another option: Don't teach valgrind, and don't teach gdb.

> That's not actually true on all OSs -- another of those pesky misconceptions.

Technically, an OS isn't even required, and neither is `malloc`, `stdin`, so on and so forth... The course could teach _embedded_ programming on a _freestanding_ implementation (see [C11/4](http://www.iso-9899.info/n1570.html#4.). Wouldn't that make things exciting for newcomers? Learning how to light up LEDs, control robots and so forth...

However, as you seem to assume various invalid _simplicities_ such as _where strings are stored_, _what character set's used_ and ... _the console_... well, I don't think it's a far stretch to assume that the OS will reclaim unfreed resources when the program terminates; after all, Windows and Unix all use virtual memory management.

Sorry, but you can't make sense arguing _for_ simplicity and then _against_ simplicity in the same post.

**Comment by Sebbyastian** [comment]
> This is by design, actually.

!["It's not a bug; it's a feature!"](https://img.memesuper.com/09b3f80db9a389c92484afd8b9f16f69_yellow-tint-screen-opt-opo-owners-request-page-2-oneplus-feature-meme_450-364.jpeg)
