### ISSUE TITLE
Undefined behaviour caused by invalid values passed to character type (`<ctype.h>`) functions.

### ISSUE THREAD

**Issue by Sebbyastian** [cs50/libcs50#68]
According to [section 7.4 of the C11 standard](http://port70.net/~nsz/c/c11/n1570.html#7.4), the argument of any `<ctype.h>` function "is an `int`, the value of which shall be representable as an `unsigned char` or shall equal the value of the macro `EOF`".

However, in numerous functions (`get_double`, `get_float`, `get_int`, `get_long_long`) the argument to `isspace` is a `char`, of which the type isn't guaranteed to be an _unsigned_ type and as a result, the value isn't guaranteed to "be representable as an `unsigned char` or shall equal the value of the macro `EOF`".

This kind of error has [questions showing assertion errors on StackOverflow](http://stackoverflow.com/questions/28513332/debug-assertation-failed-c-1-c-255). It can be reproduced for such implementations by providing input characters that have negative, non-`EOF` values.

You need to cast that expression to an `unsigned char`, before you call `isspace`, in order to avoid this problem.

**Comment by crossroads1112** [comment]
PR #70
