### ISSUE TITLE
cp: /usr/include/cs50.h: Operation not permitted

### ISSUE THREAD

**Issue by jhnath90** [cs50/libcs50#75]
I spent around 4 hours trying to debug this, I can't seem to fix it. After downloading the latest release and extracting it seems that when I run make install it fails. I tried to run each individual command as sudo and still no luck. Using El Capitan OS, bash and Vim 8. This is also my first stab at working with C.

![screen shot 2017-06-01 at 6 35 17 pm](https://cloud.githubusercontent.com/assets/13606943/26703720/1b1f9cfa-46f9-11e7-99df-43df1c8224c3.png)

**Comment by kzidane** [comment]
Apologies for the inconvenience, @jhnath90! Mind telling us what do you get when you run `sudo make install` instead, please?

**Comment by jhnath90** [comment]
No inconvenience at all @kzidane, much appreciated that you all do what you do to make this content available for the masses. I get the same output when running with sudo.

![screen shot 2017-06-01 at 6 58 07 pm](https://cloud.githubusercontent.com/assets/13606943/26704349/6e9d46ae-46fc-11e7-9e78-8dd1050edf3a.png)

**Comment by kzidane** [comment]
Oops, I didn't notice you're on Mac. AFAIK, you should install under `/usr/local/` rather than `/usr/`. Mind trying to open the `Makefile`, and replacing the value of `USR_DIR` from `/usr` to `/usr/local`, and trying again, please?

**Comment by jhnath90** [comment]
I went ahead and changed the Makefile, it still seems to produce the same error.
![screen shot 2017-06-01 at 7 06 59 pm](https://cloud.githubusercontent.com/assets/13606943/26704545/bee6037a-46fd-11e7-8b62-de972bfc8f6a.png)
![screen shot 2017-06-01 at 7 08 02 pm](https://cloud.githubusercontent.com/assets/13606943/26704560/dbe9289e-46fd-11e7-92cd-ce762b831a3e.png)

**Comment by kzidane** [comment]
Actually can you do that for the `install` target as well?
```
 install: build
     cp "$(INCLUDE_DIR)"/* /usr/local/include
     cp "$(LIB_DIR)"/* /usr/local/lib
```

instead of

```
 install: build
     cp "$(INCLUDE_DIR)"/* /usr/include
     cp "$(LIB_DIR)"/* /usr/lib
```

**Comment by jhnath90** [comment]
Thanks @kzidane, I was able to build it successfully. I appreciate all the help. It does raise another error though, I do get a segmentation fault 11 error after I run ./string. I read up on this a bit ago as it seemed like a problem that others were experiencing too. I'll trouble shoot this one myself for now, if I can't seem to figure it out then I'll open another issue. Thanks again!

**Comment by kzidane** [comment]
Glad it worked! Best if you post issues/questions related to your code on any of CS50's online communities. See for a full list of them in the [Discussion](https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/a7ec0c0a7b6e460f877da0734811c4cd/) tab on edX!

**Comment by jhnath90** [comment]
Awesome, thanks for pointing that out to me, I will post there for any further questions.
