### ISSUE TITLE
update man pages to be consistent with latest cs50.c

### ISSUE THREAD

**Issue by dmalan** [cs50/libcs50#77]
https://github.com/cs50/libcs50/tree/updating-manpages

- [x] eprintf
- [ ] get_char
- [ ] get_float
- [ ] get_int
- [ ] get_long
- [ ] get_long_long
- [ ] get_string

**Comment by kzidane** [comment]
Updated per d244a15!

**Comment by dmalan** [comment]
Thanks! Should we be committing `debian/docs/*.3` to repo, or should those be built by Travis?

**Comment by kzidane** [comment]
Oops, forgot to remove actually. Just removed per 9d30390!
