### ISSUE TITLE
Ressurect the /usr vs /usr/local discussion

### ISSUE THREAD

**Issue by crossroads1112** [cs50/libcs50#79]
Due to the recent number of students using OSX being unable to install the library due to `/usr` being write-protected, perhaps we should revisit this discussion. I would still hold that the `rpm`, `pacman` and `deb` targets should install to `/usr` since they will be managed by a package manager, but perhaps the `install` target should install to `/usr/local` since then the library would not be managed by a package manager. 

At the very least, we could allow this behavior to be changed by an environment variable as some other libraries do where `make install` would default to `/usr` but something like `INSTALL_DIR=/usr/local make install` would cause the library to be installed in `/usr/local` so we don't have to tell those students to alter the makefile manually.

**Comment by kzidane** [comment]
Sounds good! Changed `DESTDIR`'s default value to `/usr/local` per 0af40ac. deb should install to `/usr` by default, while `make install` should install to `/usr/local` by default now. Thanks!

**Comment by crossroads1112** [comment]
You should change the comment above that line as well

Also, are we no longer supporting `rpm` and `pacman` in the `launchpad` branch?

**Comment by dmalan** [comment]
Not sure if it's compelling since we're not planning to host the packages,
folks have to install fpm to use, and is simpler just to support   `make`?
