### ISSUE TITLE
Add CMakeLists.txt file

### ISSUE THREAD

**Issue by sahil56** [cs50/libcs50#87]
I do not see a **CMakeLists.txt** file in the code.
I know it won't be possible to create a _VS solution_ due to **'_attribute_' syntax error**, but there is no problem creating _CodeBlocks project_ and _other make files_.
People with MingGW can easily make use of CMakeLists file.
I tested it on my windows machine. It works fine. I can send a pull request if needed.

**Comment by crossroads1112** [comment]
We don't use CMake to build `libcs50` so there isn't much of a reason to have a `CMakeLists.txt` file. The library should be compilable on with `MinGW` without the use of CMake.

Side note: `libcs50` should be compilable under MSVC now as of ecbc40b
