### ISSUE TITLE
launchpad keeps latest version only

### ISSUE THREAD

**Issue by kzidane** [cs50/libcs50#92]

**Comment by dmalan** [comment]
How do we want to address this, @kzidane, if at all?

**Comment by kzidane** [comment]
@dmalan there doesn't seem to be a way around this per https://help.launchpad.net/Packaging/PPA

> Packages you publish in your PPA will remain there until you remove them, they're superseded by another package that you upload or the version of Ubuntu against which they're built becomes obsolete.

This is a problem if we deploy to Launchpad before we deploy `ide50` to our mirror in which case `apt` won't be able to see older versions of certain packages (e.g., `libcs50`) anymore. For example, if `ide50` v110 depends on `libcs50 (= 8.0.5)`, and we deployed `libcs50 (=8.0.6)`, but haven't released `ide50` v111 yet, running `update50` in workspaces < v110 won't upgrade any packages (e.g., won't upgrade `libcs50` to v8.0.5 because `apt` won't be able to see it).

So we'll just have to make sure to deploy our packages to Launchpad and up dependency versions in `ide50` at the same time. Alternatively, we could go back to using `>=` instead of `=`, so instead of depending on `libcs50 (= 8.0.5)` we'll need to depend on `libcs50 (>= 8.0.5)`.

**Comment by dmalan** [comment]
Feels safest to revert to `>=` then?

**Comment by kzidane** [comment]
Done per https://github.com/cs50/ide50/pull/120!
