### ISSUE TITLE
Split pane replicates file contents from one pane to the other

### ISSUE THREAD

**Issue by MadDogDean** [cs50/libcs50#96]
Don't know if this happened previously (I just updated to v101)

If two individual files are open and the "Split pane in two columns (or rows)" command is invoked, a change or edit on one file causes that files contents to be replicated and replaces the contents of the other file.

This issue seems applicable only to the CS50 IDE, I tried to replicate the problem in my personal C9 workspace and the split pane works as expected.

**Comment by kzidane** [comment]
Moved to https://github.com/cs50/harvard.cs50.droplet/issues/55!
